




// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.22 - 15.20-s024_1
// Generated on: Jun 17 2020 22:08:31

// Verification Directory fv/cmsdk_apb_uart 

module apb_uart(PCLK, PCLKG, PRESETn, PSEL, PADDR, PENABLE,
     PWRITE, PWDATA, ECOREVNUM, PRDATA, PREADY, PSLVERR, RXD, TXD,
     TXEN, BAUDTICK, TXINT, RXINT, TXOVRINT, RXOVRINT, UARTINT);
  input PCLK, PCLKG, PRESETn, PSEL, PENABLE, PWRITE, RXD;
  input [11:2] PADDR;
  input [31:0] PWDATA;
  input [3:0] ECOREVNUM;
  output [31:0] PRDATA;
  output PREADY, PSLVERR, TXD, TXEN, BAUDTICK, TXINT, RXINT, TXOVRINT,
       RXOVRINT, UARTINT;
  wire PCLK, PCLKG, PRESETn, PSEL, PENABLE, PWRITE, RXD;
  wire [11:2] PADDR;
  wire [31:0] PWDATA;
  wire [3:0] ECOREVNUM;
  wire [31:0] PRDATA;
  wire PREADY, PSLVERR, TXD, TXEN, BAUDTICK, TXINT, RXINT, TXOVRINT,
       RXOVRINT, UARTINT;
  wire [15:0] reg_baud_cntr_i;
  wire [3:0] reg_baud_cntr_f;
  wire [19:0] reg_baud_div;
  wire [7:0] reg_rx_buf;
  wire [6:0] rx_shift_buf;
  wire [3:0] rx_state;
  wire [6:0] reg_ctrl;
  wire [7:0] read_mux_byte0_reg;
  wire [3:0] tx_state;
  wire [3:0] tx_tick_cnt;
  wire [3:0] rx_tick_cnt;
  wire [2:0] rxd_lpf;
  wire [7:0] reg_tx_buf;
  wire [7:0] tx_shift_buf;
  wire baud_updated, n_0, n_1, n_5, n_6, n_8, n_9, n_10;
  wire n_12, n_14, n_17, n_18, n_19, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_29, n_30, n_33, n_34, n_35;
  wire n_41, n_43, n_44, n_46, n_47, n_48, n_50, n_52;
  wire n_53, n_54, n_56, n_58, n_60, n_61, n_65, n_70;
  wire n_71, n_77, n_79, n_86, n_88, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_114, n_115, n_124, n_125, n_127, n_131, n_133;
  wire n_134, n_136, n_137, n_138, n_139, n_145, n_149, n_152;
  wire n_153, n_154, n_155, n_156, n_171, n_180, n_181, n_182;
  wire n_183, n_184, n_186, n_187, n_188, n_189, n_190, n_192;
  wire n_199, n_200, n_203, n_204, n_205, n_211, n_212, n_214;
  wire n_215, n_218, n_219, n_220, n_229, n_232, n_233, n_241;
  wire n_242, n_243, n_244, n_251, n_253, n_254, n_255, n_260;
  wire n_265, n_270, n_274, n_275, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_296, n_297, n_299, n_301, n_302, n_303;
  wire n_306, n_307, n_308, n_309, n_310, n_318, n_321, n_323;
  wire n_326, n_329, n_330, n_334, n_336, n_337, n_338, n_340;
  wire n_342, n_343, n_344, n_346, n_348, n_349, n_352, n_353;
  wire n_354, n_356, n_357, n_358, n_359, n_360, n_361, n_363;
  wire n_364, n_365, n_367, n_368, n_369, n_370, n_371, n_373;
  wire n_376, n_377, n_378, n_379, n_380, n_382, n_383, n_384;
  wire n_385, n_386, n_389, n_390, n_391, n_392, n_394, n_395;
  wire n_396, n_397, n_398, n_399, n_400, n_402, n_403, n_404;
  wire n_405, n_406, n_407, n_408, n_409, n_410, n_412, n_413;
  wire n_414, n_416, n_417, n_418, n_419, n_420, n_421, n_422;
  wire n_423, n_424, n_425, n_427, n_430, n_431, n_436, n_443;
  wire n_444, n_446, n_448, n_449, n_450, n_453, n_454, n_455;
  wire n_456, n_457, n_459, n_460, n_461, n_462, n_463, n_464;
  wire n_465, n_466, n_467, n_468, n_469, n_470, n_471, n_472;
  wire n_473, n_474, n_475, n_476, n_477, n_478, n_479, n_480;
  wire n_481, n_482, n_483, n_484, n_485, n_486, n_487, n_488;
  wire n_489, n_491, n_492, n_493, n_494, n_495, n_496, n_497;
  wire n_498, n_499, n_500, n_502, n_503, n_504, n_505, n_507;
  wire n_508, n_509, n_511, n_513, n_514, n_515, n_517, n_518;
  wire n_519, n_520, n_521, n_524, n_525, n_526, n_527, n_528;
  wire n_529, n_530, n_531, n_532, n_533, n_534, n_535, n_536;
  wire n_537, n_538, n_539, n_540, n_541, n_542, n_543, n_544;
  wire n_546, n_547, n_548, n_551, n_552, n_553, n_554, n_555;
  wire n_556, n_557, n_558, n_559, n_560, n_562, n_566, n_567;
  wire n_568, n_569, n_570, n_572, n_573, n_574, n_576, n_577;
  wire n_578, n_579, n_580, n_582, n_583, n_584, n_585, n_586;
  wire n_587, n_588, n_589, n_590, n_591, n_592, n_593, n_596;
  wire n_599, n_600, n_601, n_602, n_605, n_606, n_607, n_608;
  wire n_609, n_610, n_612, n_613, n_615, n_616, n_617, n_618;
  wire n_619, n_621, n_622, n_623, n_625, n_626, n_674, n_675;
  wire n_676, n_677, n_678, n_679, n_680, n_681, n_682, n_683;
  wire n_684, n_685, n_686, n_687, n_688, n_689, n_690, n_691;
  wire n_692, n_693, n_694, n_695, n_764, n_847, n_851, n_861;
  wire n_862, n_867, n_886, n_887, n_891, n_896, n_897, n_902;
  wire n_903, n_906, n_909, n_933, n_947, n_948, n_949, n_951;
  wire n_952, n_967, n_968, n_974, n_975, n_976, n_977, n_979;
  wire n_983, n_986, n_989, n_993, n_994, n_995, n_996, n_998;
  wire n_999, n_1000, n_1007, n_1010, n_1016, n_1017, n_1018, n_1019;
  wire n_1020, n_1027, n_1028, n_1029, n_1030, n_1032, n_1033, n_1046;
  wire n_1047, n_1048, n_1051, n_1054, n_1055, n_1065, n_1066, n_1068;
  wire n_1070, n_1071, n_1072, n_1075, n_1076, n_1078, n_1080, n_1081;
  wire n_1084, n_1087, n_1088, n_1089, n_1090, n_1091, n_1092, n_1093;
  wire n_1094, n_1095, n_1096, n_1103, n_1104, n_1107, n_1108, n_1116;
  wire n_1118, n_1119, n_1120, n_1121, n_1122, n_1123, n_1257, n_1258;
  wire n_1259, n_1260, n_1261, n_1262, n_1264, n_1265, n_1266, n_1268;
  wire n_1269, n_1270, n_1271, n_1272, n_1273, n_1274, n_1277, n_1278;
  wire n_1281, n_1282, n_1283, n_1284, n_1285, n_1286, n_1287, n_1288;
  wire n_1289, n_1290, n_1291, n_1292, n_1293, n_1294, n_1295, n_1296;
  wire n_1297, n_1298, n_1299, n_1300, n_1301, reg_rx_overrun,
       reg_tx_overrun, rx_buf_full;
  wire rxd_sync_1, rxd_sync_2, tx_buf_full;
  assign PSLVERR = 1'b0;
  assign PREADY = 1'b1;
  assign PRDATA[20] = 1'b0;
  assign PRDATA[21] = 1'b0;
  assign PRDATA[22] = 1'b0;
  assign PRDATA[23] = 1'b0;
  assign PRDATA[24] = 1'b0;
  assign PRDATA[25] = 1'b0;
  assign PRDATA[26] = 1'b0;
  assign PRDATA[27] = 1'b0;
  assign PRDATA[28] = 1'b0;
  assign PRDATA[29] = 1'b0;
  assign PRDATA[30] = 1'b0;
  assign PRDATA[31] = 1'b0;
  DFFRHQX4 \reg_baud_cntr_i_reg[15] (.RN (PRESETn), .CK (PCLK), .D
       (n_1293), .Q (reg_baud_cntr_i[15]));
  OAI21X2 g14600(.A0 (n_391), .A1 (n_623), .B0 (reg_baud_cntr_i[15]),
       .Y (n_626));
  OAI21X2 g14605(.A0 (n_621), .A1 (n_615), .B0 (n_592), .Y (n_625));
  OAI21X2 g14609(.A0 (n_621), .A1 (n_1298), .B0 (n_588), .Y (n_622));
  OAI21X2 g14604(.A0 (n_621), .A1 (n_619), .B0 (n_617), .Y (n_623));
  OAI222X2 g14614(.A0 (n_867), .A1 (n_612), .B0 (n_621), .B1 (n_601),
       .C0 (n_600), .C1 (n_617), .Y (n_618));
  OAI221X1 g14688(.A0 (n_94), .A1 (n_593), .B0 (reg_baud_cntr_f[3]),
       .B1 (n_608), .C0 (n_609), .Y (n_616));
  NOR2BX1 g14608(.AN (n_607), .B (n_619), .Y (n_615));
  SDFFRHQX8 reg_rxintr_reg(.RN (PRESETn), .CK (PCLK), .D (n_585), .SE
       (n_586), .SI (RXINT), .Q (RXINT));
  OAI222X2 g14621(.A0 (n_896), .A1 (n_612), .B0 (n_621), .B1 (n_574),
       .C0 (n_573), .C1 (n_617), .Y (n_613));
  OAI211X1 g14692(.A0 (n_580), .A1 (n_579), .B0 (n_609), .C0 (n_608),
       .Y (n_610));
  NAND2BXL g14610(.AN (n_591), .B (n_606), .Y (n_607));
  NOR2X2 g14611(.A (reg_baud_cntr_i[13]), .B (n_606), .Y (n_619));
  SDFFRHQX4 rx_buf_full_reg(.RN (PRESETn), .CK (PCLK), .D
       (rx_buf_full), .SE (n_566), .SI (n_551), .Q (rx_buf_full));
  OAI211X1 g14709(.A0 (n_297), .A1 (n_552), .B0 (n_609), .C0 (n_572),
       .Y (n_605));
  DFFRHQX8 reg_baud_tick_reg(.RN (PRESETn), .CK (PCLK), .D (n_536), .Q
       (BAUDTICK));
  OAI222X2 g14735(.A0 (reg_baud_cntr_i[0]), .A1 (n_621), .B0 (n_468),
       .B1 (n_541), .C0 (n_540), .C1 (n_617), .Y (n_602));
  AOI2BB1X1 g14620(.A0N (n_600), .A1N (n_544), .B0 (n_1281), .Y
       (n_601));
  NAND2X2 g14617(.A (n_599), .B (n_1281), .Y (n_606));
  OAI222X2 g14625(.A0 (n_621), .A1 (n_548), .B0 (n_886), .B1 (n_612),
       .C0 (n_547), .C1 (n_617), .Y (n_596));
  INVX1 g14713(.A (n_608), .Y (n_593));
  AOI2BB2X2 g14724(.A0N (n_617), .A1N (n_591), .B0 (reg_baud_div[17]),
       .B1 (n_590), .Y (n_592));
  OAI222X1 g14721(.A0 (n_255), .A1 (n_621), .B0 (n_17), .B1 (n_612),
       .C0 (n_254), .C1 (n_617), .Y (n_589));
  AOI2BB2X2 g14723(.A0N (n_617), .A1N (n_599), .B0 (reg_baud_div[16]),
       .B1 (n_590), .Y (n_588));
  OAI222X1 g14633(.A0 (n_621), .A1 (n_503), .B0 (n_947), .B1 (n_612),
       .C0 (n_502), .C1 (n_617), .Y (n_587));
  AOI21X2 g14666(.A0 (n_99), .A1 (n_568), .B0 (n_585), .Y (n_586));
  OAI222X1 g14673(.A0 (n_344), .A1 (n_621), .B0 (n_974), .B1 (n_612),
       .C0 (n_343), .C1 (n_617), .Y (n_584));
  OAI222X1 g14725(.A0 (n_115), .A1 (n_621), .B0 (n_472), .B1 (n_612),
       .C0 (n_50), .C1 (n_617), .Y (n_583));
  OAI222X1 g14726(.A0 (n_212), .A1 (n_621), .B0 (n_475), .B1 (n_612),
       .C0 (n_211), .C1 (n_617), .Y (n_582));
  NAND2X2 g14717(.A (n_580), .B (n_579), .Y (n_608));
  OAI222X1 g14646(.A0 (n_621), .A1 (n_403), .B0 (n_967), .B1 (n_612),
       .C0 (n_402), .C1 (n_617), .Y (n_578));
  OAI222X1 g14697(.A0 (n_330), .A1 (n_621), .B0 (n_1007), .B1 (n_612),
       .C0 (n_329), .C1 (n_617), .Y (n_577));
  OAI222X1 g14638(.A0 (n_621), .A1 (n_461), .B0 (n_994), .B1 (n_612),
       .C0 (n_460), .C1 (n_617), .Y (n_576));
  AOI2BB1X1 g14626(.A0N (n_573), .A1N (n_520), .B0 (n_544), .Y (n_574));
  INVX1 g14730(.A (n_579), .Y (n_572));
  SDFFRHQX1 \reg_rx_buf_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[2]), .SE (n_570), .SI (rx_shift_buf[2]), .Q
       (reg_rx_buf[2]));
  OAI211X1 g14714(.A0 (n_525), .A1 (n_536), .B0 (n_609), .C0 (n_553),
       .Y (n_567));
  SDFFRHQX1 \reg_rx_buf_reg[7] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[7]), .SE (n_570), .SI (n_424), .Q (reg_rx_buf[7]));
  NAND2X1 g14671(.A (n_559), .B (n_1288), .Y (n_566));
  OAI32X2 g14665(.A0 (rx_state[2]), .A1 (n_528), .A2 (n_527), .B0
       (n_529), .B1 (n_515), .Y (n_562));
  OAI2BB1X1 g14664(.A0N (rx_state[0]), .A1N (n_513), .B0 (n_537), .Y
       (n_560));
  NOR2X2 g14669(.A (n_18), .B (n_559), .Y (n_585));
  OAI211X1 g14782(.A0 (n_41), .A1 (n_555), .B0 (n_467), .C0 (n_524), .Y
       (n_558));
  OAI2BB1X1 g14766(.A0N (reg_rx_buf[2]), .A1N (n_538), .B0 (n_535), .Y
       (n_557));
  OAI211X1 g14753(.A0 (n_54), .A1 (n_555), .B0 (n_534), .C0 (n_474), .Y
       (n_556));
  OAI211X1 g14754(.A0 (n_48), .A1 (n_555), .B0 (n_532), .C0 (n_478), .Y
       (n_554));
  NOR2X4 g14733(.A (reg_baud_cntr_f[1]), .B (n_553), .Y (n_579));
  INVX1 g14738(.A (n_553), .Y (n_552));
  SDFFRHQX8 reg_txintr_reg(.RN (PRESETn), .CK (PCLK), .D (n_464), .SE
       (n_465), .SI (TXINT), .Q (TXINT));
  NAND2BX2 g14668(.AN (n_570), .B (n_546), .Y (n_551));
  AOI2BB1X1 g14634(.A0N (n_547), .A1N (n_1282), .B0 (n_520), .Y
       (n_548));
  NOR2BX2 g14670(.AN (n_570), .B (n_546), .Y (n_569));
  OAI211X1 g14778(.A0 (n_58), .A1 (n_555), .B0 (n_509), .C0 (n_469), .Y
       (n_543));
  OAI211X1 g14765(.A0 (n_34), .A1 (n_555), .B0 (n_517), .C0 (n_473), .Y
       (n_542));
  AOI211X4 g14769(.A0 (n_540), .A1 (n_359), .B0 (baud_updated), .C0
       (n_505), .Y (n_541));
  OAI2BB1X1 g14770(.A0N (reg_rx_buf[7]), .A1N (n_538), .B0 (n_511), .Y
       (n_539));
  INVX4 g14739(.A (n_612), .Y (n_590));
  OAI21X2 g14672(.A0 (n_518), .A1 (n_514), .B0 (n_504), .Y (n_537));
  NOR2X2 g14631(.A (reg_baud_cntr_i[10]), .B (n_521), .Y (n_544));
  AOI221X1 g14798(.A0 (reg_ctrl[2]), .A1 (n_1283), .B0
       (reg_tx_overrun), .B1 (n_533), .C0 (n_479), .Y (n_535));
  AOI221X2 g14797(.A0 (reg_rx_overrun), .A1 (n_533), .B0 (RXOVRINT),
       .B1 (n_531), .C0 (n_480), .Y (n_534));
  AOI221X2 g14791(.A0 (tx_buf_full), .A1 (n_533), .B0 (TXINT), .B1
       (n_531), .C0 (n_471), .Y (n_532));
  OAI31X1 g14682(.A0 (n_529), .A1 (n_528), .A2 (n_527), .B0 (n_427), .Y
       (n_530));
  OAI211X1 g14771(.A0 (n_0), .A1 (n_555), .B0 (n_455), .C0 (n_476), .Y
       (n_526));
  INVX1 g14676(.A (n_570), .Y (n_559));
  NAND2X4 g14750(.A (n_525), .B (n_536), .Y (n_553));
  NOR2X6 g14751(.A (baud_updated), .B (n_536), .Y (n_612));
  AOI221X1 g14835(.A0 (read_mux_byte0_reg[1]), .A1 (n_214), .B0
       (reg_ctrl[1]), .B1 (n_1283), .C0 (n_508), .Y (n_524));
  INVX1 g14635(.A (n_521), .Y (n_520));
  OAI221X1 g14677(.A0 (n_518), .A1 (n_1284), .B0 (rx_state[0]), .B1
       (n_528), .C0 (n_507), .Y (n_519));
  AOI221X2 g14804(.A0 (n_205), .A1 (n_417), .B0
       (read_mux_byte0_reg[5]), .B1 (n_214), .C0 (n_450), .Y (n_517));
  AOI211X2 g14683(.A0 (n_514), .A1 (n_527), .B0 (n_518), .C0 (n_513),
       .Y (n_515));
  AOI221X2 g14796(.A0 (reg_baud_div[7]), .A1 (n_466), .B0
       (read_mux_byte0_reg[7]), .B1 (n_214), .C0 (n_449), .Y (n_511));
  AOI221X1 g14803(.A0 (n_1289), .A1 (n_454), .B0
       (read_mux_byte0_reg[4]), .B1 (n_214), .C0 (n_508), .Y (n_509));
  NOR2X8 g14679(.A (n_86), .B (n_507), .Y (n_570));
  NAND2X4 g14636(.A (n_547), .B (n_1282), .Y (n_521));
  NOR3X2 g14790(.A (n_540), .B (n_481), .C (n_482), .Y (n_505));
  OAI22X2 g14680(.A0 (n_171), .A1 (n_410), .B0 (n_397), .B1 (n_399), .Y
       (n_504));
  AOI2BB1X1 g14639(.A0N (n_502), .A1N (n_459), .B0 (n_1282), .Y
       (n_503));
  OAI222X1 g14777(.A0 (n_483), .A1 (n_496), .B0 (n_497), .B1 (n_495),
       .C0 (n_22), .C1 (n_494), .Y (n_499));
  OAI222X1 g14779(.A0 (n_497), .A1 (n_496), .B0 (n_491), .B1 (n_495),
       .C0 (n_53), .C1 (n_494), .Y (n_498));
  OAI222X1 g14780(.A0 (n_486), .A1 (n_496), .B0 (n_484), .B1 (n_495),
       .C0 (n_21), .C1 (n_494), .Y (n_493));
  OAI222X1 g14781(.A0 (n_491), .A1 (n_496), .B0 (n_462), .B1 (n_495),
       .C0 (n_24), .C1 (n_494), .Y (n_492));
  OAI222X1 g14785(.A0 (n_242), .A1 (n_496), .B0 (n_487), .B1 (n_495),
       .C0 (n_1), .C1 (n_494), .Y (n_489));
  OAI222X1 g14786(.A0 (n_487), .A1 (n_496), .B0 (n_486), .B1 (n_495),
       .C0 (n_25), .C1 (n_494), .Y (n_488));
  OAI222X1 g14787(.A0 (n_484), .A1 (n_496), .B0 (n_483), .B1 (n_495),
       .C0 (n_26), .C1 (n_494), .Y (n_485));
  DFFRHQX8 \reg_ctrl_reg[0] (.RN (PRESETn), .CK (PCLKG), .D (n_690), .Q
       (TXEN));
  DFFRHQX4 \reg_ctrl_reg[4] (.RN (PRESETn), .CK (PCLKG), .D (n_691), .Q
       (reg_ctrl[4]));
  AOI211X4 g14788(.A0 (reg_baud_cntr_i[0]), .A1 (n_482), .B0 (n_180),
       .C0 (n_481), .Y (n_536));
  NAND2X1 g14840(.A (n_418), .B (n_470), .Y (n_480));
  OAI221X2 g14834(.A0 (n_96), .A1 (n_477), .B0 (n_97), .B1 (n_364), .C0
       (n_385), .Y (n_479));
  AOI2BB2X1 g14836(.A0N (n_9), .A1N (n_477), .B0 (TXEN), .B1 (n_1283),
       .Y (n_478));
  AOI2BB2X1 g14837(.A0N (n_475), .A1N (n_477), .B0 (reg_ctrl[6]), .B1
       (n_1283), .Y (n_476));
  AOI2BB2X1 g14832(.A0N (n_12), .A1N (n_477), .B0 (reg_ctrl[3]), .B1
       (n_1283), .Y (n_474));
  AOI2BB2X1 g14841(.A0N (n_472), .A1N (n_477), .B0 (reg_ctrl[5]), .B1
       (n_1283), .Y (n_473));
  NAND2X1 g14842(.A (n_412), .B (n_470), .Y (n_471));
  AOI2BB2X1 g14843(.A0N (n_468), .A1N (n_477), .B0 (reg_ctrl[4]), .B1
       (n_1283), .Y (n_469));
  AOI222X1 g14897(.A0 (reg_baud_div[1]), .A1 (n_466), .B0
       (rx_buf_full), .B1 (n_533), .C0 (RXINT), .C1 (n_531), .Y
       (n_467));
  AOI21X2 g14801(.A0 (n_101), .A1 (n_568), .B0 (n_464), .Y (n_465));
  OAI221X1 g14783(.A0 (n_462), .A1 (n_414), .B0 (n_43), .B1 (n_494),
       .C0 (n_495), .Y (n_463));
  AOI2BB1X1 g14654(.A0N (n_460), .A1N (n_386), .B0 (n_459), .Y (n_461));
  NAND2X6 g14684(.A (n_518), .B (n_425), .Y (n_507));
  OAI2BB2X1 g14876(.A0N (reg_baud_div[0]), .A1N (n_457), .B0 (n_431),
       .B1 (n_457), .Y (n_456));
  AOI2BB2X1 g14838(.A0N (n_218), .A1N (n_127), .B0 (n_309), .B1
       (n_454), .Y (n_455));
  OAI32X2 g14844(.A0 (tx_state[3]), .A1 (n_154), .A2 (n_419), .B0
       (n_92), .B1 (n_396), .Y (n_453));
  AOI21X2 g14866(.A0 (n_33), .A1 (n_61), .B0 (n_448), .Y (n_450));
  AOI21X2 g14867(.A0 (n_30), .A1 (n_407), .B0 (n_448), .Y (n_449));
  SDFFRHQX4 \rx_shift_buf_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[0]), .SE (n_1284), .SI (rx_shift_buf[1]), .Q
       (rx_shift_buf[0]));
  SDFFRHQX4 \rx_shift_buf_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[3]), .SE (n_1284), .SI (rx_shift_buf[4]), .Q
       (rx_shift_buf[3]));
  SDFFRHQX4 \rx_shift_buf_reg[5] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[5]), .SE (n_1284), .SI (rx_shift_buf[6]), .Q
       (rx_shift_buf[5]));
  SDFFRHQX4 \rx_shift_buf_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[1]), .SE (n_1284), .SI (rx_shift_buf[2]), .Q
       (rx_shift_buf[1]));
  SDFFRHQX4 \rx_shift_buf_reg[4] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[4]), .SE (n_1284), .SI (rx_shift_buf[5]), .Q
       (rx_shift_buf[4]));
  OAI221X2 g14800(.A0 (n_93), .A1 (n_377), .B0 (tx_state[1]), .B1
       (n_376), .C0 (n_281), .Y (n_443));
  OAI2BB2X1 g14888(.A0N (reg_baud_div[1]), .A1N (n_457), .B0 (n_98),
       .B1 (n_457), .Y (n_436));
  OAI21X2 g14707(.A0 (n_518), .A1 (n_421), .B0 (rx_state[3]), .Y
       (n_427));
  INVX2 g14912(.A (n_470), .Y (n_508));
  NAND2X2 g14907(.A (rx_buf_full), .B (n_1288), .Y (n_546));
  INVX2 g14691(.A (n_425), .Y (n_527));
  SDFFRHQX4 \rx_shift_buf_reg[6] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[6]), .SE (n_1284), .SI (n_424), .Q
       (rx_shift_buf[6]));
  SDFFRHQX4 \rx_shift_buf_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[2]), .SE (n_1284), .SI (rx_shift_buf[3]), .Q
       (rx_shift_buf[2]));
  AOI211X2 g14845(.A0 (n_280), .A1 (n_318), .B0 (n_378), .C0 (n_352),
       .Y (n_423));
  NOR3X4 g14848(.A (n_71), .B (n_19), .C (n_494), .Y (n_464));
  NOR2X8 g14719(.A (n_409), .B (n_421), .Y (n_425));
  OAI2BB2X1 g14799(.A0N (tx_state[2]), .A1N (n_354), .B0 (n_137), .B1
       (n_419), .Y (n_420));
  AOI2BB2X1 g14898(.A0N (n_188), .A1N (n_127), .B0 (n_284), .B1
       (n_417), .Y (n_418));
  NAND2XL g14908(.A (n_457), .B (n_609), .Y (n_416));
  OAI21X1 g14802(.A0 (n_367), .A1 (n_380), .B0 (n_369), .Y (n_413));
  AOI2BB2X1 g14896(.A0N (n_181), .A1N (n_127), .B0 (n_233), .B1
       (n_417), .Y (n_412));
  AOI2BB2X2 g14708(.A0N (n_409), .A1N (n_1284), .B0 (n_409), .B1
       (n_1284), .Y (n_410));
  NOR2X2 g14806(.A (n_408), .B (n_414), .Y (n_500));
  NOR2X2 g14805(.A (n_389), .B (n_384), .Y (n_482));
  NAND3BX4 g14918(.AN (PADDR[2]), .B (n_407), .C (n_417), .Y (n_470));
  AOI21X2 g14863(.A0 (PWDATA[2]), .A1 (n_568), .B0 (n_405), .Y (n_406));
  OAI32X2 g14899(.A0 (tx_tick_cnt[3]), .A1 (n_337), .A2 (n_394), .B0
       (n_60), .B1 (n_338), .Y (n_404));
  AOI2BB1X1 g14681(.A0N (n_402), .A1N (n_342), .B0 (n_386), .Y (n_403));
  NAND2X1 g14715(.A (n_373), .B (n_399), .Y (n_400));
  AOI21X1 g14869(.A0 (PWDATA[3]), .A1 (1'b1), .B0 (n_95), .Y (n_398));
  AOI2BB1X1 g14716(.A0N (n_397), .A1N (n_424), .B0 (n_1284), .Y
       (n_513));
  OAI21X4 g14831(.A0 (n_358), .A1 (n_396), .B0 (n_390), .Y (n_495));
  OAI32X2 g14875(.A0 (tx_tick_cnt[1]), .A1 (n_368), .A2 (n_394), .B0
       (n_379), .B1 (n_349), .Y (n_395));
  NOR2X2 g14905(.A (reg_baud_cntr_i[14]), .B (n_621), .Y (n_392));
  NOR2X2 g14915(.A (n_47), .B (n_621), .Y (n_391));
  INVX1 g14990(.A (n_477), .Y (n_466));
  INVX2 g14904(.A (n_454), .Y (n_448));
  AOI32X4 g14900(.A0 (n_357), .A1 (n_346), .A2 (n_390), .B0 (n_279),
       .B1 (n_356), .Y (n_496));
  AOI31X2 g14870(.A0 (n_525), .A1 (n_383), .A2 (n_382), .B0
       (reg_baud_div[3]), .Y (n_389));
  INVX8 g14728(.A (n_1284), .Y (n_421));
  NOR2X2 g14662(.A (reg_baud_cntr_i[7]), .B (n_365), .Y (n_459));
  NOR2X2 g14911(.A (n_1010), .B (n_363), .Y (n_454));
  INVX3 g14862(.A (n_494), .Y (n_414));
  AOI32X4 g14917(.A0 (PADDR[4]), .A1 (n_136), .A2 (n_1296), .B0
       (read_mux_byte0_reg[2]), .B1 (n_214), .Y (n_385));
  INVX3 g14927(.A (n_444), .Y (n_430));
  INVX2 g14974(.A (n_538), .Y (n_555));
  NAND3X8 g15004(.A (n_232), .B (n_340), .C (n_229), .Y (n_477));
  INVX12 g14929(.A (n_446), .Y (n_457));
  AOI21X2 g14868(.A0 (n_383), .A1 (n_382), .B0 (n_525), .Y (n_384));
  AOI21X2 g14916(.A0 (n_379), .A1 (n_336), .B0 (n_348), .Y (n_380));
  AOI221X2 g14895(.A0 (TXEN), .A1 (n_370), .B0 (n_241), .B1 (n_371),
       .C0 (tx_state[0]), .Y (n_378));
  AOI21X2 g14873(.A0 (tx_buf_full), .A1 (tx_state[3]), .B0 (n_376), .Y
       (n_377));
  MXI2X1 g14752(.A (rx_tick_cnt[3]), .B (n_360), .S0 (n_1285), .Y
       (n_373));
  INVX1 g14913(.A (n_396), .Y (n_419));
  DFFRHQX4 \rx_tick_cnt_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_695),
       .Q (rx_tick_cnt[0]));
  AOI21X4 g14881(.A0 (n_303), .A1 (n_371), .B0 (n_370), .Y (n_494));
  NAND4BBX4 g14961(.AN (n_379), .BN (n_368), .C (n_367), .D (n_302), .Y
       (n_369));
  INVX1 g14687(.A (n_365), .Y (n_386));
  INVX2 g14989(.A (n_364), .Y (n_531));
  INVX4 g14926(.A (n_363), .Y (n_417));
  NOR3X4 g15002(.A (n_282), .B (n_334), .C (n_1291), .Y (n_533));
  NOR2X2 g14988(.A (n_307), .B (n_1291), .Y (n_538));
  NOR3X8 g14943(.A (PADDR[2]), .B (n_361), .C (n_1277), .Y (n_444));
  NOR2X8 g14945(.A (n_306), .B (n_1291), .Y (n_446));
  NAND3X8 g14968(.A (n_609), .B (n_359), .C (n_481), .Y (n_621));
  NOR2X4 g14906(.A (n_357), .B (n_356), .Y (n_358));
  BUFX20 g14924(.A (n_321), .Y (PRDATA[19]));
  OAI21X1 g14874(.A0 (tx_state[3]), .A1 (n_371), .B0 (n_153), .Y
       (n_354));
  NOR2X1 g14768(.A (n_301), .B (n_323), .Y (n_353));
  INVX1 g14903(.A (n_376), .Y (n_352));
  BUFX20 g14921(.A (n_326), .Y (PRDATA[10]));
  INVX2 g14925(.A (n_348), .Y (n_349));
  NOR2X6 g14919(.A (n_346), .B (n_356), .Y (n_396));
  BUFX20 g14949(.A (n_1081), .Y (PRDATA[18]));
  AOI2BB1X1 g14710(.A0N (n_343), .A1N (n_274), .B0 (n_342), .Y (n_344));
  BUFX20 g14953(.A (n_310), .Y (PRDATA[11]));
  AOI21X2 g14965(.A0 (n_337), .A1 (n_336), .B0 (n_65), .Y (n_338));
  NAND2X6 g14941(.A (PADDR[5]), .B (n_1296), .Y (n_363));
  NAND3BX4 g15003(.AN (n_334), .B (n_407), .C (n_229), .Y (n_364));
  NAND2X2 g14689(.A (n_402), .B (n_342), .Y (n_365));
  NOR2X6 g14942(.A (n_1010), .B (n_1277), .Y (n_568));
  NOR2X8 g14944(.A (n_283), .B (n_1277), .Y (n_422));
  AOI2BB1X1 g14755(.A0N (n_329), .A1N (n_253), .B0 (n_274), .Y (n_330));
  BUFX20 g14947(.A (n_1070), .Y (PRDATA[13]));
  NOR2X4 g14933(.A (n_1274), .B (n_1020), .Y (n_326));
  BUFX20 g14922(.A (n_1091), .Y (PRDATA[16]));
  NOR2X4 g14937(.A (n_909), .B (n_1020), .Y (n_321));
  BUFX20 g14946(.A (n_1068), .Y (PRDATA[14]));
  OAI21X4 g14938(.A0 (tx_tick_cnt[0]), .A1 (n_318), .B0 (BAUDTICK), .Y
       (n_348));
  NAND2X4 g14910(.A (tx_state[0]), .B (n_371), .Y (n_376));
  BUFX20 g14950(.A (n_1093), .Y (PRDATA[12]));
  BUFX20 g14951(.A (n_1094), .Y (PRDATA[9]));
  NOR2X4 g14966(.A (n_1000), .B (n_1020), .Y (n_310));
  OAI2BB2X1 g15039(.A0N (PADDR[4]), .A1N (n_361), .B0 (n_35), .B1
       (n_308), .Y (n_309));
  NAND3X2 g15036(.A (n_79), .B (n_199), .C (n_127), .Y (n_307));
  NAND3X8 g14976(.A (n_1010), .B (n_1287), .C (n_232), .Y (n_306));
  NOR2X6 g15072(.A (PADDR[2]), .B (n_214), .Y (n_340));
  INVX2 g14970(.A (n_303), .Y (n_390));
  INVX2 g14972(.A (n_302), .Y (n_394));
  MXI2X1 g14833(.A (rx_tick_cnt[2]), .B (n_296), .S0 (n_251), .Y
       (n_301));
  NOR2BX1 g14864(.AN (n_244), .B (n_323), .Y (n_299));
  DFFSHQX8 reg_txd_reg(.SN (PRESETn), .CK (PCLK), .D (n_243), .Q (TXD));
  OAI2BB1X4 g14939(.A0N (reg_baud_div[2]), .A1N (n_297), .B0 (n_260),
       .Y (n_382));
  SDFFSHQX4 \rxd_lpf_reg[2] (.SN (PRESETn), .CK (PCLK), .D
       (rxd_lpf[2]), .SE (BAUDTICK), .SI (rxd_lpf[1]), .Q (rxd_lpf[2]));
  SDFFSHQX4 \rxd_lpf_reg[1] (.SN (PRESETn), .CK (PCLK), .D
       (rxd_lpf[1]), .SE (BAUDTICK), .SI (rxd_lpf[0]), .Q (rxd_lpf[1]));
  SDFFSHQX4 \rxd_lpf_reg[0] (.SN (PRESETn), .CK (PCLK), .D
       (rxd_lpf[0]), .SE (BAUDTICK), .SI (rxd_sync_2), .Q (rxd_lpf[0]));
  INVX3 g14954(.A (n_371), .Y (n_356));
  NOR2X2 g14718(.A (reg_baud_cntr_i[5]), .B (n_275), .Y (n_342));
  INVX20 g15026(.A (n_265), .Y (UARTINT));
  OAI22X2 g15035(.A0 (n_61), .A1 (n_283), .B0 (n_1010), .B1 (n_282), .Y
       (n_284));
  NAND4X6 g14994(.A (n_357), .B (tx_state[0]), .C (n_280), .D (n_270),
       .Y (n_281));
  NAND2X4 g15097(.A (n_100), .B (n_127), .Y (n_334));
  NOR2X4 g14986(.A (n_65), .B (n_318), .Y (n_302));
  NAND2X4 g14984(.A (n_155), .B (n_279), .Y (n_303));
  NAND3X8 g14981(.A (n_91), .B (n_88), .C (n_192), .Y (n_481));
  INVX1 g14764(.A (n_275), .Y (n_274));
  OAI21X4 g14967(.A0 (n_65), .A1 (n_270), .B0 (n_56), .Y (n_371));
  NOR2X8 g15042(.A (RXOVRINT), .B (n_190), .Y (n_265));
  INVX2 g15027(.A (n_279), .Y (n_370));
  INVX2 g15008(.A (n_318), .Y (n_336));
  OAI21X4 g14991(.A0 (n_580), .A1 (n_125), .B0 (n_156), .Y (n_260));
  AOI2BB1X1 g14839(.A0N (n_254), .A1N (n_134), .B0 (n_253), .Y (n_255));
  MXI2X1 g14955(.A (rx_tick_cnt[1]), .B (n_204), .S0 (n_203), .Y
       (n_244));
  OAI21X2 g14975(.A0 (n_138), .A1 (n_242), .B0 (n_241), .Y (n_243));
  NAND2X4 g14772(.A (n_329), .B (n_253), .Y (n_275));
  BUFX20 g15051(.A (n_189), .Y (PRDATA[3]));
  OAI21X2 g15087(.A0 (n_61), .A1 (n_361), .B0 (n_283), .Y (n_233));
  INVX2 g15032(.A (n_1291), .Y (n_229));
  BUFX20 g15058(.A (n_182), .Y (PRDATA[0]));
  BUFX20 g15057(.A (n_183), .Y (PRDATA[1]));
  BUFX20 g15052(.A (n_219), .Y (PRDATA[6]));
  BUFX20 g15053(.A (n_215), .Y (PRDATA[4]));
  BUFX20 g15054(.A (n_187), .Y (PRDATA[5]));
  BUFX20 g15055(.A (n_186), .Y (PRDATA[7]));
  BUFX20 g15056(.A (n_184), .Y (PRDATA[2]));
  NAND3X8 g15048(.A (tx_buf_full), .B (n_220), .C (n_152), .Y (n_279));
  NOR2X6 g15025(.A (n_220), .B (n_241), .Y (n_318));
  NOR2X4 g15062(.A (n_218), .B (n_214), .Y (n_219));
  NOR2X4 g15063(.A (n_46), .B (n_214), .Y (n_215));
  AOI2BB1X1 g14959(.A0N (n_211), .A1N (n_114), .B0 (n_134), .Y (n_212));
  INVX8 g15103(.A (n_205), .Y (n_282));
  NOR2X4 g14983(.A (n_204), .B (n_203), .Y (n_251));
  NOR2X6 g15152(.A (reg_ctrl[6]), .B (n_65), .Y (n_280));
  INVX1 g14973(.A (n_399), .Y (n_323));
  NAND2X4 g15017(.A (n_199), .B (n_1287), .Y (n_200));
  NOR4X8 g15037(.A (reg_baud_cntr_i[6]), .B (reg_baud_cntr_i[15]), .C
       (reg_baud_cntr_i[14]), .D (n_1297), .Y (n_192));
  NAND2X8 g15091(.A (n_145), .B (n_97), .Y (n_190));
  NOR2X4 g15061(.A (n_188), .B (n_214), .Y (n_189));
  NOR2X4 g15065(.A (n_14), .B (n_214), .Y (n_187));
  NOR2X4 g15066(.A (n_29), .B (n_214), .Y (n_186));
  NOR2X4 g15068(.A (n_5), .B (n_214), .Y (n_184));
  NOR2X4 g15069(.A (n_44), .B (n_214), .Y (n_183));
  NOR2X4 g15070(.A (n_181), .B (n_214), .Y (n_182));
  NAND2X8 g15075(.A (n_609), .B (n_180), .Y (n_617));
  NOR2X4 g15134(.A (PADDR[3]), .B (PADDR[4]), .Y (n_205));
  INVX2 g15104(.A (n_180), .Y (n_359));
  INVX8 g15106(.A (n_407), .Y (n_308));
  NAND2X4 g14987(.A (n_131), .B (n_171), .Y (n_399));
  NOR2X4 g14878(.A (reg_baud_cntr_i[3]), .B (n_139), .Y (n_253));
  OAI21X4 g15038(.A0 (reg_baud_cntr_f[2]), .A1 (n_124), .B0 (n_6), .Y
       (n_156));
  NAND4X6 g15040(.A (tx_buf_full), .B (tx_state[3]), .C (n_154), .D
       (n_153), .Y (n_155));
  NAND2X6 g15021(.A (tx_tick_cnt[3]), .B (n_133), .Y (n_270));
  INVX3 g15060(.A (n_152), .Y (n_241));
  NAND2X4 g15064(.A (n_102), .B (n_764), .Y (n_149));
  NOR2X6 g15130(.A (TXINT), .B (RXINT), .Y (n_145));
  NAND2X8 g15155(.A (BAUDTICK), .B (rx_tick_cnt[0]), .Y (n_203));
  NOR2X6 g15135(.A (TXEN), .B (reg_ctrl[1]), .Y (n_180));
  NOR2X8 g15137(.A (PADDR[4]), .B (n_361), .Y (n_407));
  INVX12 g15125(.A (n_127), .Y (n_214));
  NOR2X4 g15071(.A (tx_state[0]), .B (n_137), .Y (n_138));
  OAI21X4 g15088(.A0 (PADDR[2]), .A1 (n_10), .B0 (n_283), .Y (n_136));
  INVX1 g14969(.A (n_139), .Y (n_134));
  NOR2X6 g15073(.A (tx_state[1]), .B (n_137), .Y (n_152));
  INVX2 g15076(.A (n_133), .Y (n_337));
  INVX2 g15028(.A (n_131), .Y (n_424));
  INVX20 g15143(.A (n_97), .Y (TXOVRINT));
  NOR2X8 g15138(.A (PWRITE), .B (n_70), .Y (n_127));
  INVX2 g15139(.A (n_124), .Y (n_125));
  INVX2 g15145(.A (n_153), .Y (n_346));
  SDFFSHQX1 rxd_sync_2_reg(.SN (PRESETn), .CK (PCLK), .D (rxd_sync_2),
       .SE (reg_ctrl[1]), .SI (rxd_sync_1), .Q (rxd_sync_2));
  INVX3 g15146(.A (n_137), .Y (n_357));
  AOI21X2 g15094(.A0 (reg_baud_cntr_i[1]), .A1 (reg_baud_cntr_i[0]),
       .B0 (n_114), .Y (n_115));
  NOR3X8 g15098(.A (n_379), .B (n_367), .C (n_368), .Y (n_133));
  NOR2X6 g15131(.A (PADDR[4]), .B (PADDR[9]), .Y (n_199));
  ACHCONX2 g15049(.A (rxd_lpf[1]), .B (rxd_lpf[2]), .CI (rxd_lpf[0]),
       .CON (n_131));
  SDFFSHQX1 rxd_sync_1_reg(.SN (PRESETn), .CK (PCLK), .D (rxd_sync_1),
       .SE (reg_ctrl[1]), .SI (RXD), .Q (rxd_sync_1));
  NAND2X4 g14982(.A (n_211), .B (n_114), .Y (n_139));
  NOR2X4 g15128(.A (n_361), .B (n_431), .Y (n_101));
  NOR2X4 g15149(.A (PADDR[9]), .B (n_1010), .Y (n_100));
  NOR2X4 g15148(.A (n_361), .B (n_98), .Y (n_99));
  NAND2X4 g15153(.A (n_96), .B (reg_baud_cntr_f[1]), .Y (n_383));
  NOR2X8 g15154(.A (n_27), .B (n_95), .Y (RXOVRINT));
  NAND2X4 g15151(.A (reg_baud_div[0]), .B (n_94), .Y (n_124));
  NOR2X6 g15158(.A (n_93), .B (n_220), .Y (n_153));
  NAND2X4 g15157(.A (rx_state[1]), .B (n_514), .Y (n_528));
  NAND2X8 g15159(.A (n_154), .B (n_92), .Y (n_137));
  NOR4X8 g15093(.A (reg_baud_cntr_i[2]), .B (reg_baud_cntr_i[9]), .C
       (reg_baud_cntr_i[13]), .D (reg_baud_cntr_i[12]), .Y (n_91));
  NOR4X8 g15092(.A (reg_baud_cntr_i[3]), .B (reg_baud_cntr_i[5]), .C
       (reg_baud_cntr_i[11]), .D (reg_baud_cntr_i[7]), .Y (n_88));
  NAND2X4 g15126(.A (rx_state[3]), .B (n_529), .Y (n_86));
  NOR4X8 g15095(.A (rx_state[0]), .B (rx_state[1]), .C (rx_state[3]),
       .D (rx_state[2]), .Y (n_171));
  INVX4 g15105(.A (n_79), .Y (n_283));
  NAND2X8 g15147(.A (PADDR[8]), .B (PADDR[10]), .Y (n_77));
  NOR2X6 g15133(.A (reg_baud_cntr_i[1]), .B (reg_baud_cntr_i[0]), .Y
       (n_114));
  INVX8 g15282(.A (PSEL), .Y (n_70));
  NAND2X6 g15156(.A (reg_tx_overrun), .B (reg_ctrl[4]), .Y (n_97));
  NOR2X8 g15136(.A (PADDR[2]), .B (PADDR[3]), .Y (n_79));
  INVX20 g15171(.A (PADDR[6]), .Y (n_52));
  INVX16 g15161(.A (ECOREVNUM[2]), .Y (n_35));
  INVX16 g15167(.A (ECOREVNUM[1]), .Y (n_33));
  INVX16 g15241(.A (ECOREVNUM[3]), .Y (n_30));
  INVX16 g15204(.A (PWDATA[1]), .Y (n_98));
  INVX8 g15341(.A (BAUDTICK), .Y (n_65));
  INVX20 g15237(.A (PADDR[3]), .Y (n_361));
  INVX16 g15233(.A (PADDR[4]), .Y (n_61));
  INVX20 g15261(.A (PADDR[11]), .Y (n_102));
  INVX8 g15323(.A (TXEN), .Y (n_71));
  INVX16 g15294(.A (PWDATA[0]), .Y (n_431));
  OR3X6 g2(.A (n_1290), .B (n_398), .C (n_569), .Y (n_674));
  NAND2BX4 g15461(.AN (n_422), .B (n_675), .Y (n_676));
  OR2X6 g15462(.A (n_408), .B (n_414), .Y (n_675));
  MX2X4 g15463(.A (PWDATA[10]), .B (reg_baud_div[10]), .S0 (n_457), .Y
       (n_677));
  MX2X4 g15464(.A (PWDATA[13]), .B (reg_baud_div[13]), .S0 (n_457), .Y
       (n_678));
  MX2X4 g15465(.A (PWDATA[12]), .B (reg_baud_div[12]), .S0 (n_457), .Y
       (n_679));
  MX2X4 g15466(.A (PWDATA[11]), .B (reg_baud_div[11]), .S0 (n_457), .Y
       (n_680));
  MX2X4 g15467(.A (PWDATA[9]), .B (reg_baud_div[9]), .S0 (n_457), .Y
       (n_681));
  MX2X4 g15468(.A (PWDATA[15]), .B (reg_baud_div[15]), .S0 (n_457), .Y
       (n_682));
  MX2X4 g15469(.A (PWDATA[16]), .B (reg_baud_div[16]), .S0 (n_457), .Y
       (n_683));
  MX2X4 g15470(.A (PWDATA[17]), .B (reg_baud_div[17]), .S0 (n_457), .Y
       (n_684));
  MX2X4 g15471(.A (PWDATA[18]), .B (reg_baud_div[18]), .S0 (n_457), .Y
       (n_685));
  MX2X4 g15472(.A (PWDATA[19]), .B (reg_baud_div[19]), .S0 (n_457), .Y
       (n_686));
  MX2X4 g15473(.A (PWDATA[2]), .B (reg_baud_div[2]), .S0 (n_457), .Y
       (n_687));
  MX2X4 g15474(.A (PWDATA[8]), .B (reg_baud_div[8]), .S0 (n_457), .Y
       (n_688));
  MX2X4 g15475(.A (PWDATA[14]), .B (reg_baud_div[14]), .S0 (n_457), .Y
       (n_689));
  MXI2X1 g15476(.A (n_431), .B (n_71), .S0 (n_430), .Y (n_690));
  MX2X4 g15477(.A (PWDATA[4]), .B (reg_ctrl[4]), .S0 (n_430), .Y
       (n_691));
  MX2X4 g15478(.A (PWDATA[5]), .B (reg_ctrl[5]), .S0 (n_430), .Y
       (n_692));
  MXI2X1 g15479(.A (n_394), .B (BAUDTICK), .S0 (tx_tick_cnt[0]), .Y
       (n_693));
  NOR2X8 g15480(.A (n_694), .B (n_323), .Y (n_695));
  MX2X4 g15481(.A (n_65), .B (BAUDTICK), .S0 (rx_tick_cnt[0]), .Y
       (n_694));
  NOR2X8 g15534_dup(.A (PADDR[5]), .B (PADDR[6]), .Y (n_764));
  NOR2X8 g90(.A (PWRITE), .B (PADDR[11]), .Y (n_847));
  NOR4X8 g29(.A (n_861), .B (PADDR[10]), .C (PADDR[8]), .D (PADDR[7]),
       .Y (n_862));
  NOR4X8 g15631(.A (n_886), .B (PADDR[6]), .C (PADDR[5]), .D
       (PADDR[2]), .Y (n_887));
  NOR4X8 g25(.A (n_896), .B (PADDR[5]), .C (PADDR[6]), .D (PADDR[2]),
       .Y (n_897));
  NAND2X6 g48(.A (n_903), .B (n_1301), .Y (n_909));
  NOR2X6 g49(.A (PADDR[11]), .B (n_902), .Y (n_903));
  NAND2X8 g51(.A (PSEL), .B (PADDR[4]), .Y (n_902));
  NOR2X8 g53(.A (PADDR[9]), .B (PADDR[3]), .Y (n_906));
  NOR2X4 g15656(.A (n_949), .B (n_951), .Y (n_952));
  INVX4 g15657(.A (n_948), .Y (n_949));
  NOR2X8 g15658(.A (n_947), .B (PADDR[7]), .Y (n_948));
  INVX16 g15669(.A (PADDR[4]), .Y (n_968));
  NAND2X4 g15672(.A (n_979), .B (n_1116), .Y (n_983));
  NOR2X6 g57(.A (n_976), .B (n_951), .Y (n_979));
  INVX4 g59(.A (n_975), .Y (n_976));
  NOR2X8 g60(.A (n_974), .B (PADDR[7]), .Y (n_975));
  INVX8 g61(.A (n_977), .Y (n_951));
  NOR2X8 g62(.A (PADDR[10]), .B (PADDR[8]), .Y (n_977));
  INVX20 g45(.A (PSEL), .Y (n_986));
  NOR2X8 g43(.A (PWRITE), .B (PADDR[11]), .Y (n_989));
  NAND2X6 g15680(.A (n_993), .B (n_999), .Y (n_1000));
  INVX2 fopt15681(.A (n_1017), .Y (n_993));
  NOR2X6 g15682(.A (n_996), .B (n_998), .Y (n_999));
  INVX4 g15683(.A (n_995), .Y (n_996));
  NOR2X8 g15684(.A (n_994), .B (PWRITE), .Y (n_995));
  NAND2X8 g15686(.A (PSEL), .B (n_102), .Y (n_998));
  NAND2X4 g13(.A (PADDR[4]), .B (n_1016), .Y (n_1017));
  NOR2X8 g14(.A (PADDR[3]), .B (PADDR[9]), .Y (n_1016));
  NAND2X8 g15702(.A (n_1018), .B (n_1019), .Y (n_1020));
  NOR3X8 g15703(.A (PADDR[5]), .B (PADDR[6]), .C (PADDR[2]), .Y
       (n_1018));
  NOR3X8 g41(.A (PADDR[8]), .B (PADDR[10]), .C (PADDR[7]), .Y (n_1019));
  NOR2X8 g95(.A (n_1028), .B (n_1029), .Y (n_1030));
  INVX6 g98(.A (n_1027), .Y (n_1028));
  NOR2X8 g99(.A (n_1007), .B (PADDR[6]), .Y (n_1027));
  NAND2X8 g96(.A (n_10), .B (n_1010), .Y (n_1029));
  NOR3X8 g91(.A (PADDR[11]), .B (PWRITE), .C (n_986), .Y (n_1032));
  NOR3X8 g92(.A (PADDR[7]), .B (PADDR[10]), .C (PADDR[8]), .Y (n_1033));
  BUFX20 g15709(.A (n_1096), .Y (PRDATA[17]));
  INVX2 g15718(.A (n_1119), .Y (n_1051));
  NAND2X4 g15720(.A (n_1046), .B (n_1047), .Y (n_1048));
  NOR2X8 g15721(.A (n_891), .B (PADDR[7]), .Y (n_1046));
  NOR2X8 g15722(.A (PADDR[10]), .B (PADDR[8]), .Y (n_1047));
  NAND2X4 g15724(.A (n_862), .B (n_1118), .Y (n_1054));
  INVX1 fopt15725(.A (n_1055), .Y (n_232));
  INVX1 fopt2(.A (n_1118), .Y (n_1055));
  BUFX20 g15729(.A (n_1066), .Y (PRDATA[8]));
  NOR2X4 g15730(.A (n_1264), .B (n_1065), .Y (n_1066));
  NAND2X4 g15732(.A (n_1030), .B (n_1116), .Y (n_1065));
  NOR2X4 g15733(.A (n_1264), .B (n_1260), .Y (n_1068));
  NOR2X4 g15735(.A (n_1264), .B (n_1259), .Y (n_1070));
  NOR2X6 g15736(.A (n_1020), .B (n_1080), .Y (n_1081));
  NAND2X4 g15737(.A (n_1076), .B (n_1273), .Y (n_1080));
  NOR2X6 g15738(.A (n_1072), .B (n_1075), .Y (n_1076));
  INVX4 g15739(.A (n_1071), .Y (n_1072));
  NOR2X8 g58(.A (n_933), .B (PADDR[3]), .Y (n_1071));
  NAND2X8 g15740(.A (n_8), .B (PADDR[4]), .Y (n_1075));
  INVX20 g15741(.A (PADDR[9]), .Y (n_8));
  INVX6 g15745(.A (n_847), .Y (n_1078));
  INVX20 g31(.A (PADDR[2]), .Y (n_1010));
  NOR2X8 g15749(.A (PADDR[6]), .B (PADDR[5]), .Y (n_1084));
  NOR2X4 g15750(.A (n_1051), .B (n_1090), .Y (n_1091));
  INVX4 fopt15751(.A (n_1089), .Y (n_1090));
  NOR2X8 g15752(.A (n_1087), .B (n_1088), .Y (n_1089));
  NAND2X8 g64(.A (n_1010), .B (n_1084), .Y (n_1087));
  NAND2X8 g65(.A (PSEL), .B (n_989), .Y (n_1088));
  NOR2X4 g15753(.A (n_1262), .B (n_1092), .Y (n_1093));
  INVX2 fopt66(.A (n_1089), .Y (n_1092));
  NOR2X4 g15754(.A (n_983), .B (n_1090), .Y (n_1094));
  NOR2X4 g15755(.A (n_1095), .B (n_1054), .Y (n_1096));
  INVX4 fopt67(.A (n_1089), .Y (n_1095));
  NOR2X6 g77(.A (n_1104), .B (n_1107), .Y (n_1108));
  INVX4 g79(.A (n_1103), .Y (n_1104));
  NOR2X8 g80(.A (n_867), .B (PADDR[2]), .Y (n_1103));
  NAND2X8 g78(.A (n_10), .B (n_52), .Y (n_1107));
  INVX20 g81(.A (PADDR[5]), .Y (n_10));
  INVX4 g18(.A (n_1123), .Y (n_1116));
  INVX2 g17(.A (n_1121), .Y (n_1118));
  NOR2X2 g16(.A (n_1048), .B (n_1123), .Y (n_1119));
  NAND2X2 g23_dup(.A (PADDR[4]), .B (n_1120), .Y (n_1121));
  NOR2X2 g24_dup(.A (PADDR[3]), .B (PADDR[9]), .Y (n_1120));
  NAND2X8 g23(.A (PADDR[4]), .B (n_1122), .Y (n_1123));
  NOR2X8 g24(.A (PADDR[3]), .B (PADDR[9]), .Y (n_1122));
  NAND2X4 g15856(.A (n_1258), .B (n_887), .Y (n_1259));
  NOR3X8 g15857(.A (PADDR[3]), .B (PADDR[9]), .C (n_1257), .Y (n_1258));
  INVX20 g15858(.A (PADDR[4]), .Y (n_1257));
  NAND2X4 g15859(.A (n_897), .B (n_1258), .Y (n_1260));
  NAND2X4 g15860(.A (n_952), .B (n_1261), .Y (n_1262));
  NOR3X8 g76_dup(.A (PADDR[3]), .B (PADDR[9]), .C (n_1257), .Y
       (n_1261));
  NAND2X8 g15862(.A (n_1032), .B (n_1033), .Y (n_1264));
  BUFX20 g15863(.A (n_1266), .Y (PRDATA[15]));
  NOR2X4 g15864(.A (n_1265), .B (n_1264), .Y (n_1266));
  NAND2X4 g15865(.A (n_1108), .B (n_1261), .Y (n_1265));
  NAND2X4 g33(.A (n_1272), .B (n_1273), .Y (n_1274));
  NOR2X6 g34(.A (n_1269), .B (n_1271), .Y (n_1272));
  INVX8 g38(.A (n_1268), .Y (n_1269));
  NOR2X8 g39(.A (n_967), .B (PADDR[9]), .Y (n_1268));
  INVX4 g15866(.A (n_1270), .Y (n_1271));
  NOR2X8 g36(.A (PADDR[3]), .B (n_968), .Y (n_1270));
  NOR2X8 g37(.A (n_70), .B (n_1078), .Y (n_1273));
  DFFRX4 \tx_tick_cnt_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_404), .Q
       (tx_tick_cnt[3]), .QN (n_60));
  SDFFRX4 \reg_rx_buf_reg[4] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[4]), .SE (n_570), .SI (rx_shift_buf[4]), .Q
       (reg_rx_buf[4]), .QN (n_58));
  SDFFRX4 \reg_ctrl_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[6]), .SE (n_444), .SI (PWDATA[6]), .Q (reg_ctrl[6]),
       .QN (n_56));
  SDFFRX4 \reg_rx_buf_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[3]), .SE (n_570), .SI (rx_shift_buf[3]), .Q
       (reg_rx_buf[3]), .QN (n_54));
  SDFFRX4 \reg_tx_buf_reg[5] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[5]), .SE (n_422), .SI (PWDATA[5]), .Q
       (reg_tx_buf[5]), .QN (n_53));
  DFFRX4 \reg_baud_cntr_i_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (n_583), .Q (reg_baud_cntr_i[1]), .QN (n_50));
  SDFFRX4 \reg_rx_buf_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[0]), .SE (n_570), .SI (rx_shift_buf[0]), .Q
       (reg_rx_buf[0]), .QN (n_48));
  DFFRX4 \reg_baud_cntr_i_reg[14] (.RN (PRESETn), .CK (PCLK), .D
       (n_1295), .Q (reg_baud_cntr_i[14]), .QN (n_47));
  DFFRX4 \read_mux_byte0_reg_reg[4] (.RN (PRESETn), .CK (PCLKG), .D
       (n_543), .Q (read_mux_byte0_reg[4]), .QN (n_46));
  DFFRX4 \read_mux_byte0_reg_reg[1] (.RN (PRESETn), .CK (PCLKG), .D
       (n_558), .Q (read_mux_byte0_reg[1]), .QN (n_44));
  SDFFRX4 \reg_tx_buf_reg[7] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[7]), .SE (n_422), .SI (PWDATA[7]), .Q
       (reg_tx_buf[7]), .QN (n_43));
  SDFFRX4 \reg_rx_buf_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[1]), .SE (n_570), .SI (rx_shift_buf[1]), .Q
       (reg_rx_buf[1]), .QN (n_41));
  SDFFRX4 \reg_rx_buf_reg[5] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[5]), .SE (n_570), .SI (rx_shift_buf[5]), .Q
       (reg_rx_buf[5]), .QN (n_34));
  DFFRX4 \read_mux_byte0_reg_reg[7] (.RN (PRESETn), .CK (PCLKG), .D
       (n_539), .Q (read_mux_byte0_reg[7]), .QN (n_29));
  DFFRX4 \reg_ctrl_reg[5] (.RN (PRESETn), .CK (PCLKG), .D (n_692), .Q
       (reg_ctrl[5]), .QN (n_27));
  SDFFRX4 \reg_tx_buf_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[3]), .SE (n_422), .SI (PWDATA[3]), .Q
       (reg_tx_buf[3]), .QN (n_26));
  SDFFRX4 \reg_tx_buf_reg[1] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[1]), .SE (n_422), .SI (PWDATA[1]), .Q
       (reg_tx_buf[1]), .QN (n_25));
  SDFFRX4 \reg_tx_buf_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[6]), .SE (n_422), .SI (PWDATA[6]), .Q
       (reg_tx_buf[6]), .QN (n_24));
  DFFRX4 \read_mux_byte0_reg_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (n_556), .Q (read_mux_byte0_reg[3]), .QN (n_188));
  DFFRX4 \reg_baud_cntr_i_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (n_589), .Q (reg_baud_cntr_i[3]), .QN (n_254));
  DFFRX4 \tx_shift_buf_reg[6] (.RN (PRESETn), .CK (PCLK), .D (n_492),
       .Q (tx_shift_buf[6]), .QN (n_491));
  DFFRX4 \tx_state_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_453), .Q
       (tx_state[3]), .QN (n_92));
  DFFRX4 \tx_shift_buf_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_489),
       .Q (tx_shift_buf[0]), .QN (n_242));
  SDFFRX4 \reg_baud_div_reg[5] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[5]), .SE (n_446), .SI (PWDATA[5]), .Q
       (reg_baud_div[5]), .QN (n_472));
  SDFFRX4 \reg_baud_div_reg[4] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[4]), .SE (n_446), .SI (PWDATA[4]), .Q
       (reg_baud_div[4]), .QN (n_468));
  DFFRX4 \reg_baud_cntr_i_reg[5] (.RN (PRESETn), .CK (PCLK), .D
       (n_584), .Q (reg_baud_cntr_i[5]), .QN (n_343));
  DFFRX4 \tx_shift_buf_reg[4] (.RN (PRESETn), .CK (PCLK), .D (n_499),
       .Q (tx_shift_buf[4]), .QN (n_483));
  DFFRX4 \read_mux_byte0_reg_reg[0] (.RN (PRESETn), .CK (PCLKG), .D
       (n_554), .Q (read_mux_byte0_reg[0]), .QN (n_181));
  SDFFRX4 \reg_ctrl_reg[1] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[1]), .SE (n_444), .SI (PWDATA[1]), .Q (reg_ctrl[1]),
       .QN (n_397));
  DFFRX4 reg_tx_overrun_reg(.RN (PRESETn), .CK (PCLK), .D (n_1278), .Q
       (reg_tx_overrun), .QN (n_405));
  DFFRX4 \reg_baud_cntr_i_reg[4] (.RN (PRESETn), .CK (PCLK), .D
       (n_577), .Q (reg_baud_cntr_i[4]), .QN (n_329));
  DFFRX4 \reg_baud_cntr_i_reg[6] (.RN (PRESETn), .CK (PCLK), .D
       (n_578), .Q (reg_baud_cntr_i[6]), .QN (n_402));
  DFFRX4 \reg_baud_cntr_f_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (n_610), .Q (reg_baud_cntr_f[2]), .QN (n_580));
  DFFRX4 \reg_baud_cntr_i_reg[12] (.RN (PRESETn), .CK (PCLK), .D
       (n_622), .Q (reg_baud_cntr_i[12]), .QN (n_599));
  DFFRX4 \tx_tick_cnt_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_413), .Q
       (tx_tick_cnt[2]), .QN (n_367));
  DFFRX4 \reg_baud_cntr_i_reg[8] (.RN (PRESETn), .CK (PCLK), .D
       (n_587), .Q (reg_baud_cntr_i[8]), .QN (n_502));
  DFFRX4 \tx_state_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_423), .Q
       (tx_state[0]), .QN (n_220));
  SDFFRX4 baud_updated_reg(.RN (PRESETn), .CK (PCLK), .D
       (baud_updated), .SE (n_416), .SI (n_446), .Q (baud_updated), .QN
       (n_609));
  SDFFRX4 \reg_tx_buf_reg[4] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[4]), .SE (n_422), .SI (PWDATA[4]), .Q
       (reg_tx_buf[4]), .QN (n_22));
  SDFFRX4 \reg_tx_buf_reg[2] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[2]), .SE (n_422), .SI (PWDATA[2]), .Q
       (reg_tx_buf[2]), .QN (n_21));
  SDFFRX4 \reg_ctrl_reg[2] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[2]), .SE (n_444), .SI (PWDATA[2]), .Q (reg_ctrl[2]),
       .QN (n_19));
  SDFFRX4 \reg_ctrl_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[3]), .SE (n_444), .SI (PWDATA[3]), .Q (reg_ctrl[3]),
       .QN (n_18));
  SDFFRX4 \reg_baud_div_reg[7] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[7]), .SE (n_446), .SI (PWDATA[7]), .Q
       (reg_baud_div[7]), .QN (n_17));
  DFFRX4 \read_mux_byte0_reg_reg[5] (.RN (PRESETn), .CK (PCLKG), .D
       (n_542), .Q (read_mux_byte0_reg[5]), .QN (n_14));
  SDFFRX4 \reg_baud_div_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[3]), .SE (n_446), .SI (PWDATA[3]), .Q
       (reg_baud_div[3]), .QN (n_12));
  DFFRX4 \reg_baud_div_reg[0] (.RN (PRESETn), .CK (PCLKG), .D (n_456),
       .Q (reg_baud_div[0]), .QN (n_9));
  DFFRX4 \reg_baud_div_reg[1] (.RN (PRESETn), .CK (PCLKG), .D (n_436),
       .Q (reg_baud_div[1]), .QN (n_6));
  DFFRX4 \read_mux_byte0_reg_reg[2] (.RN (PRESETn), .CK (PCLKG), .D
       (n_557), .Q (read_mux_byte0_reg[2]), .QN (n_5));
  SDFFRX4 \reg_tx_buf_reg[0] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[0]), .SE (n_422), .SI (PWDATA[0]), .Q
       (reg_tx_buf[0]), .QN (n_1));
  SDFFRX4 \reg_rx_buf_reg[6] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[6]), .SE (n_570), .SI (rx_shift_buf[6]), .Q
       (reg_rx_buf[6]), .QN (n_0));
  DFFRX4 \rx_tick_cnt_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_353), .Q
       (rx_tick_cnt[2]), .QN (n_296));
  DFFRX4 \read_mux_byte0_reg_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (n_526), .Q (read_mux_byte0_reg[6]), .QN (n_218));
  DFFRX4 \tx_shift_buf_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_493),
       .Q (tx_shift_buf[2]), .QN (n_486));
  DFFRX4 \tx_shift_buf_reg[7] (.RN (PRESETn), .CK (PCLK), .D (n_463),
       .Q (tx_shift_buf[7]), .QN (n_462));
  DFFRX4 \reg_baud_cntr_i_reg[7] (.RN (PRESETn), .CK (PCLK), .D
       (n_576), .Q (reg_baud_cntr_i[7]), .QN (n_460));
  SDFFRX4 \reg_baud_div_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[6]), .SE (n_446), .SI (PWDATA[6]), .Q
       (reg_baud_div[6]), .QN (n_475));
  DFFRX4 tx_buf_full_reg(.RN (PRESETn), .CK (PCLK), .D (n_676), .Q
       (tx_buf_full), .QN (n_408));
  DFFRX4 \tx_shift_buf_reg[5] (.RN (PRESETn), .CK (PCLK), .D (n_498),
       .Q (tx_shift_buf[5]), .QN (n_497));
  DFFRX4 \reg_baud_cntr_f_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (n_616), .Q (reg_baud_cntr_f[3]), .QN (n_94));
  DFFRX4 \rx_tick_cnt_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_299), .Q
       (rx_tick_cnt[1]), .QN (n_204));
  DFFRX4 \tx_shift_buf_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_485),
       .Q (tx_shift_buf[3]), .QN (n_484));
  DFFRX4 \reg_baud_div_reg[2] (.RN (PRESETn), .CK (PCLKG), .D (n_687),
       .Q (reg_baud_div[2]), .QN (n_96));
  DFFRX4 \reg_baud_cntr_f_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (n_605), .Q (reg_baud_cntr_f[1]), .QN (n_297));
  DFFRX4 \reg_baud_cntr_i_reg[11] (.RN (PRESETn), .CK (PCLK), .D
       (n_618), .Q (reg_baud_cntr_i[11]), .QN (n_600));
  DFFRX4 \tx_state_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_443), .Q
       (tx_state[1]), .QN (n_93));
  DFFRX4 \reg_baud_cntr_i_reg[13] (.RN (PRESETn), .CK (PCLK), .D
       (n_625), .Q (reg_baud_cntr_i[13]), .QN (n_591));
  DFFRX4 \tx_shift_buf_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_488),
       .Q (tx_shift_buf[1]), .QN (n_487));
  DFFRX4 reg_rx_overrun_reg(.RN (PRESETn), .CK (PCLK), .D (n_674), .Q
       (reg_rx_overrun), .QN (n_95));
  DFFRX4 \rx_tick_cnt_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_400), .Q
       (rx_tick_cnt[3]), .QN (n_360));
  DFFRX4 \rx_state_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_562), .Q
       (rx_state[2]), .QN (n_529));
  DFFRX4 \reg_baud_cntr_i_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (n_582), .Q (reg_baud_cntr_i[2]), .QN (n_211));
  DFFRX4 \reg_baud_cntr_i_reg[10] (.RN (PRESETn), .CK (PCLK), .D
       (n_613), .Q (reg_baud_cntr_i[10]), .QN (n_573));
  DFFRX4 \reg_baud_cntr_i_reg[9] (.RN (PRESETn), .CK (PCLK), .D
       (n_596), .Q (reg_baud_cntr_i[9]), .QN (n_547));
  DFFRX4 \tx_tick_cnt_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_693), .Q
       (tx_tick_cnt[0]), .QN (n_368));
  DFFRX4 \tx_state_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_420), .Q
       (tx_state[2]), .QN (n_154));
  DFFRX4 \reg_baud_cntr_i_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (n_602), .Q (reg_baud_cntr_i[0]), .QN (n_540));
  DFFRX4 \rx_state_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_560), .Q
       (rx_state[0]), .QN (n_409));
  DFFRX4 \rx_state_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_530), .Q
       (rx_state[3]), .QN (n_514));
  DFFRX4 \reg_baud_cntr_f_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (n_567), .Q (reg_baud_cntr_f[0]), .QN (n_525));
  DFFRX4 \tx_tick_cnt_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_395), .Q
       (tx_tick_cnt[1]), .QN (n_379));
  DFFRX4 \rx_state_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_519), .Q
       (rx_state[1]), .QN (n_518));
  DFFRX4 \reg_baud_div_reg[19] (.RN (PRESETn), .CK (PCLKG), .D (n_686),
       .Q (reg_baud_div[19]), .QN (n_851));
  DFFRX4 \reg_baud_div_reg[17] (.RN (PRESETn), .CK (PCLKG), .D (n_684),
       .Q (reg_baud_div[17]), .QN (n_861));
  DFFRX4 \reg_baud_div_reg[15] (.RN (PRESETn), .CK (PCLKG), .D (n_682),
       .Q (reg_baud_div[15]), .QN (n_867));
  DFFRX4 \reg_baud_div_reg[13] (.RN (PRESETn), .CK (PCLKG), .D (n_678),
       .Q (reg_baud_div[13]), .QN (n_886));
  DFFRX4 \reg_baud_div_reg[16] (.RN (PRESETn), .CK (PCLKG), .D (n_683),
       .Q (reg_baud_div[16]), .QN (n_891));
  DFFRX4 \reg_baud_div_reg[14] (.RN (PRESETn), .CK (PCLKG), .D (n_689),
       .Q (reg_baud_div[14]), .QN (n_896));
  DFFRX4 \reg_baud_div_reg[18] (.RN (PRESETn), .CK (PCLKG), .D (n_685),
       .Q (reg_baud_div[18]), .QN (n_933));
  DFFRX4 \reg_baud_div_reg[12] (.RN (PRESETn), .CK (PCLKG), .D (n_679),
       .Q (reg_baud_div[12]), .QN (n_947));
  DFFRX4 \reg_baud_div_reg[10] (.RN (PRESETn), .CK (PCLKG), .D (n_677),
       .Q (reg_baud_div[10]), .QN (n_967));
  DFFRX4 \reg_baud_div_reg[9] (.RN (PRESETn), .CK (PCLKG), .D (n_681),
       .Q (reg_baud_div[9]), .QN (n_974));
  DFFRX4 \reg_baud_div_reg[11] (.RN (PRESETn), .CK (PCLKG), .D (n_680),
       .Q (reg_baud_div[11]), .QN (n_994));
  DFFRX4 \reg_baud_div_reg[8] (.RN (PRESETn), .CK (PCLKG), .D (n_688),
       .Q (reg_baud_div[8]), .QN (n_1007));
  OR2X6 g16053(.A (n_200), .B (n_1291), .Y (n_1277));
  AO21X4 g16054(.A0 (n_500), .A1 (n_422), .B0 (n_406), .Y (n_1278));
  NOR2BX4 g16057(.AN (n_544), .B (reg_baud_cntr_i[11]), .Y (n_1281));
  NOR2BX4 g16058(.AN (n_459), .B (reg_baud_cntr_i[8]), .Y (n_1282));
  NOR4BX4 g16059(.AN (n_340), .B (PADDR[9]), .C (n_308), .D (n_1291),
       .Y (n_1283));
  NOR2BX4 g16060(.AN (n_1285), .B (n_360), .Y (n_1284));
  NOR2BX4 g16061(.AN (n_251), .B (n_296), .Y (n_1285));
  INVXL g16062(.A (n_1286), .Y (n_1287));
  NAND3BX4 g16063(.AN (PENABLE), .B (PWRITE), .C (PSEL), .Y (n_1286));
  NAND2BX4 g16064(.AN (PENABLE), .B (n_538), .Y (n_1288));
  NAND2BX4 g16065(.AN (ECOREVNUM[0]), .B (n_407), .Y (n_1289));
  NOR2BX4 g16066(.AN (reg_rx_overrun), .B (n_568), .Y (n_1290));
  NAND2BX1 g16067(.AN (n_149), .B (n_1019), .Y (n_1291));
  NOR3BX4 g16068(.AN (PADDR[7]), .B (n_52), .C (n_77), .Y (n_1292));
  OAI2BB1X4 g16069(.A0N (reg_baud_div[19]), .A1N (n_590), .B0 (n_626),
       .Y (n_1293));
  INVXL g3(.A (n_1294), .Y (n_1295));
  AOI222X4 g16070(.A0 (reg_baud_div[18]), .A1 (n_590), .B0 (n_392), .B1
       (n_619), .C0 (n_623), .C1 (reg_baud_cntr_i[14]), .Y (n_1294));
  NOR4BX4 g16071(.AN (n_1292), .B (n_214), .C (n_102), .D (n_8), .Y
       (n_1296));
  NAND4BBX4 g16072(.AN (reg_baud_cntr_i[1]), .BN (reg_baud_cntr_i[4]),
       .C (n_502), .D (n_573), .Y (n_1297));
  OA21X4 g16073(.A0 (n_599), .A1 (n_1281), .B0 (n_606), .Y (n_1298));
  INVX3 g4(.A (n_1300), .Y (n_1301));
  NAND2X8 g16074(.A (n_1299), .B (n_906), .Y (n_1300));
  NOR2X8 g16075(.A (n_851), .B (PWRITE), .Y (n_1299));
endmodule
