
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep 23 2024 19:30:05 IST (Sep 23 2024 14:00:05 UTC)

// Verification Directory fv/apb_uart 

module apb_uart(PCLK, PCLKG, PRESETn, PSEL, PADDR, PENABLE, PWRITE,
     PWDATA, ECOREVNUM, PRDATA, PREADY, PSLVERR, RXD, TXD, TXEN,
     BAUDTICK, TXINT, RXINT, TXOVRINT, RXOVRINT, UARTINT);
  input PCLK, PCLKG, PRESETn, PSEL, PENABLE, PWRITE, RXD;
  input [11:2] PADDR;
  input [31:0] PWDATA;
  input [3:0] ECOREVNUM;
  output [31:0] PRDATA;
  output PREADY, PSLVERR, TXD, TXEN, BAUDTICK, TXINT, RXINT, TXOVRINT,
       RXOVRINT, UARTINT;
  wire PCLK, PCLKG, PRESETn, PSEL, PENABLE, PWRITE, RXD;
  wire [11:2] PADDR;
  wire [31:0] PWDATA;
  wire [3:0] ECOREVNUM;
  wire [31:0] PRDATA;
  wire PREADY, PSLVERR, TXD, TXEN, BAUDTICK, TXINT, RXINT, TXOVRINT,
       RXOVRINT, UARTINT;
  wire [19:0] reg_baud_div;
  wire [6:0] reg_ctrl;
  wire [7:0] reg_rx_buf;
  wire [6:0] rx_shift_buf;
  wire [7:0] reg_tx_buf;
  wire [2:0] rxd_lpf;
  wire [3:0] tx_state;
  wire [3:0] rx_state;
  wire [3:0] rx_tick_cnt;
  wire [15:0] reg_baud_cntr_i;
  wire [3:0] tx_tick_cnt;
  wire [7:0] read_mux_byte0_reg;
  wire [3:0] reg_baud_cntr_f;
  wire baud_updated, n_2, n_3, n_4, n_7, n_11, n_13, n_15;
  wire n_16, n_20, n_23, n_28, n_31, n_32, n_36, n_37;
  wire n_38, n_39, n_40, n_42, n_45, n_49, n_51, n_55;
  wire n_57, n_59, n_62, n_63, n_64, n_66, n_67, n_68;
  wire n_69, n_72, n_73, n_74, n_75, n_76, n_78, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_87, n_89, n_90;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_126, n_128, n_129, n_130, n_132;
  wire n_135, n_140, n_141, n_142, n_143, n_144, n_146, n_147;
  wire n_148, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_169, n_170, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_185, n_191, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_201, n_202, n_206;
  wire n_207, n_208, n_209, n_210, n_216, n_217, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_230, n_231;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_245;
  wire n_246, n_247, n_248, n_249, n_250, n_252, n_256, n_257;
  wire n_258, n_259, n_261, n_262, n_263, n_264, n_266, n_267;
  wire n_268, n_269, n_271, n_272, n_273, n_276, n_277, n_278;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292;
  wire n_293, n_294, n_295, n_298, n_300, n_304, n_305, n_311;
  wire n_312, n_313, n_314, n_315, n_316, n_317, n_319, n_320;
  wire n_322, n_324, n_325, n_327, n_328, n_331, n_332, n_333;
  wire n_335, n_339, n_341, n_345, n_347, n_350, n_351, n_355;
  wire n_362, n_366, n_372, n_374, n_375, n_381, n_387, n_388;
  wire n_393, n_401, n_411, n_415, n_426, n_428, n_429, n_432;
  wire n_433, n_434, n_435, n_437, n_438, n_439, n_440, n_441;
  wire n_442, n_445, n_447, n_451, n_452, n_458, n_490, n_501;
  wire n_506, n_510, n_512, n_516, n_522, n_523, n_545, n_549;
  wire n_550, n_561, n_563, n_564, n_565, n_571, n_575, n_581;
  wire n_594, n_595, n_597, n_598, n_604, n_611, n_614, n_620;
  wire n_624, n_627, n_628, n_629, n_630, n_631, n_632, n_633;
  wire n_634, n_635, n_636, n_637, n_638, n_639, n_640, n_641;
  wire n_642, n_644, n_645, n_646, n_650, n_651, n_652, n_653;
  wire n_654, n_656, n_658, n_659, n_660, n_661, n_662, n_663;
  wire n_664, n_665, n_666, n_667, n_668, n_669, n_670, n_671;
  wire n_672, n_673, n_696, n_697, n_698, n_699, n_700, n_701;
  wire n_702, n_703, n_704, n_705, n_706, n_707, n_708, n_709;
  wire n_710, n_720, n_721, n_722, n_723, n_724, n_725, n_726;
  wire n_727, n_728, n_729, n_730, n_731, n_732, n_733, n_734;
  wire n_735, n_736, n_737, n_738, n_750, n_751, n_752, n_753;
  wire n_794, n_796, n_798, n_799, n_802, n_803, n_805, n_809;
  wire n_810, n_811, n_812, n_813, n_814, n_815, n_816, n_817;
  wire n_818, n_819, n_820, n_821, n_822, n_823, reg_rx_overrun,
       reg_tx_overrun;
  wire rx_buf_full, rxd_sync_1, rxd_sync_2, tx_buf_full;
  assign PSLVERR = 1'b0;
  assign PREADY = 1'b1;
  assign PRDATA[20] = 1'b0;
  assign PRDATA[21] = 1'b0;
  assign PRDATA[22] = 1'b0;
  assign PRDATA[23] = 1'b0;
  assign PRDATA[24] = 1'b0;
  assign PRDATA[25] = 1'b0;
  assign PRDATA[26] = 1'b0;
  assign PRDATA[27] = 1'b0;
  assign PRDATA[28] = 1'b0;
  assign PRDATA[29] = 1'b0;
  assign PRDATA[30] = 1'b0;
  assign PRDATA[31] = 1'b0;
  SDFFRXL baud_updated_reg(.RN (PRESETn), .CK (PCLK), .D
       (baud_updated), .SI (n_654), .SE (n_736), .Q (baud_updated), .QN
       (n_720));
  SDFFRXL \reg_baud_div_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[3]), .SI (PWDATA[3]), .SE (n_654), .Q
       (reg_baud_div[3]), .QN (n_818));
  SDFFRXL \reg_baud_div_reg[4] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[4]), .SI (PWDATA[4]), .SE (n_654), .Q
       (reg_baud_div[4]), .QN (n_733));
  SDFFRXL \reg_baud_div_reg[5] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[5]), .SI (PWDATA[5]), .SE (n_654), .Q
       (reg_baud_div[5]), .QN (n_732));
  SDFFRXL \reg_baud_div_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[6]), .SI (PWDATA[6]), .SE (n_654), .Q
       (reg_baud_div[6]), .QN (n_731));
  SDFFRXL \reg_baud_div_reg[7] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_baud_div[7]), .SI (PWDATA[7]), .SE (n_654), .Q
       (reg_baud_div[7]), .QN (n_817));
  SDFFRXL \reg_ctrl_reg[1] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[1]), .SI (PWDATA[1]), .SE (n_651), .Q (reg_ctrl[1]),
       .QN (n_737));
  SDFFRXL \reg_ctrl_reg[2] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[2]), .SI (PWDATA[2]), .SE (n_651), .Q (reg_ctrl[2]),
       .QN (n_815));
  SDFFRXL \reg_ctrl_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[3]), .SI (PWDATA[3]), .SE (n_651), .Q (reg_ctrl[3]),
       .QN (n_816));
  SDFFRXL \reg_ctrl_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_ctrl[6]), .SI (PWDATA[6]), .SE (n_651), .Q (reg_ctrl[6]),
       .QN (n_796));
  SDFFRXL \reg_rx_buf_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[0]), .SI (rx_shift_buf[0]), .SE (n_652), .Q
       (reg_rx_buf[0]), .QN (n_802));
  SDFFRXL \reg_rx_buf_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[1]), .SI (rx_shift_buf[1]), .SE (n_652), .Q
       (reg_rx_buf[1]), .QN (n_805));
  SDFFRHQX1 \reg_rx_buf_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[2]), .SI (rx_shift_buf[2]), .SE (n_652), .Q
       (reg_rx_buf[2]));
  SDFFRXL \reg_rx_buf_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[3]), .SI (rx_shift_buf[3]), .SE (n_652), .Q
       (reg_rx_buf[3]), .QN (n_798));
  SDFFRXL \reg_rx_buf_reg[4] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[4]), .SI (rx_shift_buf[4]), .SE (n_652), .Q
       (reg_rx_buf[4]), .QN (n_794));
  SDFFRXL \reg_rx_buf_reg[5] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[5]), .SI (rx_shift_buf[5]), .SE (n_652), .Q
       (reg_rx_buf[5]), .QN (n_809));
  SDFFRXL \reg_rx_buf_reg[6] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[6]), .SI (rx_shift_buf[6]), .SE (n_652), .Q
       (reg_rx_buf[6]), .QN (n_820));
  SDFFRHQX1 \reg_rx_buf_reg[7] (.RN (PRESETn), .CK (PCLK), .D
       (reg_rx_buf[7]), .SI (n_59), .SE (n_652), .Q (reg_rx_buf[7]));
  SDFFRHQX1 reg_rxintr_reg(.RN (PRESETn), .CK (PCLK), .D (n_722), .SI
       (RXINT), .SE (n_721), .Q (RXINT));
  SDFFRXL \reg_tx_buf_reg[0] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[0]), .SI (PWDATA[0]), .SE (n_650), .Q
       (reg_tx_buf[0]), .QN (n_819));
  SDFFRXL \reg_tx_buf_reg[1] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[1]), .SI (PWDATA[1]), .SE (n_650), .Q
       (reg_tx_buf[1]), .QN (n_811));
  SDFFRXL \reg_tx_buf_reg[2] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[2]), .SI (PWDATA[2]), .SE (n_650), .Q
       (reg_tx_buf[2]), .QN (n_814));
  SDFFRXL \reg_tx_buf_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[3]), .SI (PWDATA[3]), .SE (n_650), .Q
       (reg_tx_buf[3]), .QN (n_810));
  SDFFRXL \reg_tx_buf_reg[4] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[4]), .SI (PWDATA[4]), .SE (n_650), .Q
       (reg_tx_buf[4]), .QN (n_813));
  SDFFRXL \reg_tx_buf_reg[5] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[5]), .SI (PWDATA[5]), .SE (n_650), .Q
       (reg_tx_buf[5]), .QN (n_799));
  SDFFRXL \reg_tx_buf_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[6]), .SI (PWDATA[6]), .SE (n_650), .Q
       (reg_tx_buf[6]), .QN (n_812));
  SDFFRXL \reg_tx_buf_reg[7] (.RN (PRESETn), .CK (PCLKG), .D
       (reg_tx_buf[7]), .SI (PWDATA[7]), .SE (n_650), .Q
       (reg_tx_buf[7]), .QN (n_803));
  SDFFRHQX1 reg_txintr_reg(.RN (PRESETn), .CK (PCLK), .D (n_735), .SI
       (TXINT), .SE (n_734), .Q (TXINT));
  SDFFRHQX1 rx_buf_full_reg(.RN (PRESETn), .CK (PCLK), .D
       (rx_buf_full), .SI (n_724), .SE (n_723), .Q (rx_buf_full));
  SDFFRHQX1 \rx_shift_buf_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[0]), .SI (rx_shift_buf[1]), .SE (n_653), .Q
       (rx_shift_buf[0]));
  SDFFRHQX1 \rx_shift_buf_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[1]), .SI (rx_shift_buf[2]), .SE (n_653), .Q
       (rx_shift_buf[1]));
  SDFFRHQX1 \rx_shift_buf_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[2]), .SI (rx_shift_buf[3]), .SE (n_653), .Q
       (rx_shift_buf[2]));
  SDFFRHQX1 \rx_shift_buf_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[3]), .SI (rx_shift_buf[4]), .SE (n_653), .Q
       (rx_shift_buf[3]));
  SDFFRHQX1 \rx_shift_buf_reg[4] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[4]), .SI (rx_shift_buf[5]), .SE (n_653), .Q
       (rx_shift_buf[4]));
  SDFFRHQX1 \rx_shift_buf_reg[5] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[5]), .SI (rx_shift_buf[6]), .SE (n_653), .Q
       (rx_shift_buf[5]));
  SDFFRHQX1 \rx_shift_buf_reg[6] (.RN (PRESETn), .CK (PCLK), .D
       (rx_shift_buf[6]), .SI (n_59), .SE (n_653), .Q
       (rx_shift_buf[6]));
  SDFFSHQX1 \rxd_lpf_reg[0] (.SN (PRESETn), .CK (PCLK), .D
       (rxd_lpf[0]), .SI (rxd_sync_2), .SE (BAUDTICK), .Q (rxd_lpf[0]));
  SDFFSHQX1 \rxd_lpf_reg[1] (.SN (PRESETn), .CK (PCLK), .D
       (rxd_lpf[1]), .SI (rxd_lpf[0]), .SE (BAUDTICK), .Q (rxd_lpf[1]));
  SDFFSHQX1 \rxd_lpf_reg[2] (.SN (PRESETn), .CK (PCLK), .D
       (rxd_lpf[2]), .SI (rxd_lpf[1]), .SE (BAUDTICK), .Q (rxd_lpf[2]));
  SDFFSHQX1 rxd_sync_1_reg(.SN (PRESETn), .CK (PCLK), .D (rxd_sync_1),
       .SI (RXD), .SE (reg_ctrl[1]), .Q (rxd_sync_1));
  SDFFSHQX1 rxd_sync_2_reg(.SN (PRESETn), .CK (PCLK), .D (rxd_sync_2),
       .SI (rxd_sync_1), .SE (reg_ctrl[1]), .Q (rxd_sync_2));
  INVXL g13094(.A (n_700), .Y (n_59));
  INVXL g13100(.A (n_673), .Y (n_651));
  INVXL g13095(.A (n_750), .Y (n_654));
  INVXL g13096(.A (n_751), .Y (n_653));
  INVXL g13099(.A (n_752), .Y (RXOVRINT));
  INVXL g13098(.A (n_753), .Y (TXOVRINT));
  INVXL g13101(.A (n_702), .Y (n_650));
  INVXL g13097(.A (n_701), .Y (n_652));
  INVXL g13102(.A (reg_baud_div[0]), .Y (n_646));
  DFFSHQX1 reg_txd_reg(.SN (PRESETn), .CK (PCLK), .D (n_636), .Q (TXD));
  AOI21XL g13845(.A0 (PWDATA[0]), .A1 (n_642), .B0 (n_735), .Y (n_734));
  AOI21XL g13846(.A0 (PWDATA[1]), .A1 (n_642), .B0 (n_722), .Y (n_721));
  NOR3BXL g13847(.AN (TXEN), .B (n_815), .C (n_727), .Y (n_735));
  NOR2XL g13848(.A (n_816), .B (n_701), .Y (n_722));
  NAND2XL g13849(.A (n_640), .B (n_701), .Y (n_723));
  NAND2XL g13850(.A (n_656), .B (n_701), .Y (n_724));
  NAND4BXL g13851(.AN (tx_state[2]), .B (tx_buf_full), .C (n_604), .D
       (n_644), .Y (n_727));
  NAND3BXL g13852(.AN (rx_state[2]), .B (rx_state[3]), .C (n_645), .Y
       (n_701));
  NOR2XL g13854(.A (rx_state[1]), .B (n_667), .Y (n_645));
  NAND2BXL g13855(.AN (n_751), .B (rx_state[0]), .Y (n_667));
  MXI2XL g13856(.A (tx_state[1]), .B (n_699), .S0 (tx_state[3]), .Y
       (n_644));
  NAND2BXL g13857(.AN (n_658), .B (rx_tick_cnt[3]), .Y (n_751));
  NAND2XL g13858(.A (tx_state[0]), .B (n_738), .Y (n_699));
  NAND2BXL g13859(.AN (n_666), .B (rx_tick_cnt[2]), .Y (n_658));
  NAND2BXL g13860(.AN (n_672), .B (rx_tick_cnt[1]), .Y (n_666));
  OAI21XL g13861(.A0 (n_661), .A1 (n_45), .B0 (n_796), .Y (n_738));
  NAND2XL g13862(.A (rx_tick_cnt[0]), .B (BAUDTICK), .Y (n_672));
  NOR2BXL g13865(.AN (PADDR[3]), .B (n_660), .Y (n_642));
  INVX1 g13866(.A (n_641), .Y (n_726));
  NAND3BXL g13867(.AN (PADDR[2]), .B (PADDR[3]), .C (n_639), .Y
       (n_673));
  AOI211XL g13868(.A0 (n_728), .A1 (reg_baud_cntr_i[0]), .B0 (n_620),
       .C0 (n_729), .Y (n_641));
  NAND2XL g13869(.A (n_750), .B (n_720), .Y (n_736));
  NAND2XL g13870(.A (PADDR[2]), .B (n_639), .Y (n_660));
  NAND2XL g13871(.A (n_611), .B (n_639), .Y (n_702));
  NAND2XL g13872(.A (rx_buf_full), .B (n_640), .Y (n_656));
  OR2X1 g13873(.A (n_662), .B (n_638), .Y (n_750));
  OR2X1 g13874(.A (PENABLE), .B (n_725), .Y (n_640));
  NOR2XL g13875(.A (PADDR[4]), .B (n_638), .Y (n_639));
  NOR2BXL g13876(.AN (reg_baud_div[12]), .B (n_730), .Y (PRDATA[12]));
  NOR2BXL g13877(.AN (reg_baud_div[14]), .B (n_730), .Y (PRDATA[14]));
  NOR2BXL g13878(.AN (reg_baud_div[15]), .B (n_730), .Y (PRDATA[15]));
  NOR2BXL g13879(.AN (reg_baud_div[13]), .B (n_730), .Y (PRDATA[13]));
  NOR2BXL g13880(.AN (reg_baud_div[19]), .B (n_730), .Y (PRDATA[19]));
  NOR2BXL g13881(.AN (reg_baud_div[11]), .B (n_730), .Y (PRDATA[11]));
  NOR2BXL g13882(.AN (reg_baud_div[10]), .B (n_730), .Y (PRDATA[10]));
  NOR2BXL g13883(.AN (reg_baud_div[9]), .B (n_730), .Y (PRDATA[9]));
  NOR2BXL g13884(.AN (reg_baud_div[16]), .B (n_730), .Y (PRDATA[16]));
  NOR2BXL g13885(.AN (reg_baud_div[17]), .B (n_730), .Y (PRDATA[17]));
  NOR2BXL g13886(.AN (reg_baud_div[18]), .B (n_730), .Y (PRDATA[18]));
  NOR2BXL g13887(.AN (reg_baud_div[8]), .B (n_730), .Y (PRDATA[8]));
  NAND4XL g13888(.A (n_614), .B (n_629), .C (n_634), .D (n_635), .Y
       (n_729));
  NAND4BXL g13889(.AN (PENABLE), .B (PSEL), .C (PWRITE), .D (n_633), .Y
       (n_638));
  OR3X1 g13890(.A (PADDR[4]), .B (n_669), .C (n_663), .Y (n_725));
  OAI21XL g13891(.A0 (n_598), .A1 (n_707), .B0 (n_637), .Y (n_728));
  OAI222XL g13893(.A0 (n_631), .A1 (n_632), .B0 (n_597), .B1
       (reg_baud_div[3]), .C0 (n_594), .C1 (reg_baud_div[2]), .Y
       (n_637));
  OR2X1 g13894(.A (n_662), .B (n_663), .Y (n_730));
  OAI2BB1XL g13896(.A0N (n_706), .A1N (n_659), .B0 (n_671), .Y (n_636));
  CLKINVX1 g13897(.A (n_635), .Y (n_665));
  NOR4BXL g13898(.AN (n_627), .B (reg_baud_cntr_i[7]), .C
       (reg_baud_cntr_i[6]), .D (reg_baud_cntr_i[5]), .Y (n_634));
  NAND2BXL g13899(.AN (n_703), .B (tx_tick_cnt[3]), .Y (n_661));
  NOR2XL g13900(.A (reg_baud_cntr_i[14]), .B (n_670), .Y (n_635));
  NAND3XL g13901(.A (n_752), .B (n_753), .C (n_628), .Y (UARTINT));
  OAI22XL g13902(.A0 (n_624), .A1 (rxd_lpf[1]), .B0 (rxd_lpf[0]), .B1
       (rxd_lpf[2]), .Y (n_700));
  NOR4BXL g13903(.AN (n_630), .B (PADDR[5]), .C (PADDR[11]), .D
       (PADDR[9]), .Y (n_633));
  NOR2BXL g13904(.AN (read_mux_byte0_reg[4]), .B (n_704), .Y
       (PRDATA[4]));
  NOR2BXL g13905(.AN (read_mux_byte0_reg[7]), .B (n_704), .Y
       (PRDATA[7]));
  NOR2BXL g13906(.AN (n_708), .B (n_704), .Y (PRDATA[6]));
  OR2X1 g13907(.A (tx_state[0]), .B (n_698), .Y (n_659));
  NAND2BXL g13908(.AN (n_664), .B (n_705), .Y (n_703));
  OR2X1 g13909(.A (reg_baud_cntr_i[13]), .B (n_697), .Y (n_670));
  OR2X1 g13910(.A (tx_state[1]), .B (n_698), .Y (n_671));
  NAND2XL g13911(.A (PADDR[4]), .B (n_611), .Y (n_662));
  AOI211XL g13912(.A0 (n_595), .A1 (reg_baud_cntr_f[2]), .B0
       (reg_baud_cntr_f[3]), .C0 (n_646), .Y (n_632));
  NOR2BXL g13913(.AN (n_709), .B (n_704), .Y (PRDATA[3]));
  NOR2BXL g13914(.AN (read_mux_byte0_reg[2]), .B (n_704), .Y
       (PRDATA[2]));
  NOR2BXL g13915(.AN (read_mux_byte0_reg[1]), .B (n_704), .Y
       (PRDATA[1]));
  NOR2BXL g13916(.AN (n_710), .B (n_704), .Y (PRDATA[0]));
  AO22X1 g13917(.A0 (reg_baud_div[2]), .A1 (n_594), .B0
       (reg_baud_div[1]), .B1 (n_15), .Y (n_631));
  NOR4XL g13918(.A (PADDR[6]), .B (PADDR[7]), .C (PADDR[8]), .D
       (PADDR[10]), .Y (n_630));
  NOR4XL g13919(.A (reg_baud_cntr_i[15]), .B (reg_baud_cntr_i[8]), .C
       (reg_baud_cntr_i[4]), .D (reg_baud_cntr_i[1]), .Y (n_629));
  NOR2BXL g13920(.AN (read_mux_byte0_reg[5]), .B (n_704), .Y
       (PRDATA[5]));
  NOR2XL g13921(.A (RXINT), .B (TXINT), .Y (n_628));
  NOR2XL g13922(.A (reg_baud_cntr_i[3]), .B (reg_baud_cntr_i[2]), .Y
       (n_627));
  AND2X1 g13923(.A (rxd_lpf[2]), .B (rxd_lpf[0]), .Y (n_624));
  NAND2XL g13924(.A (reg_tx_overrun), .B (reg_ctrl[4]), .Y (n_753));
  NAND2XL g13925(.A (reg_rx_overrun), .B (reg_ctrl[5]), .Y (n_752));
  OR2X1 g13926(.A (tx_state[2]), .B (tx_state[3]), .Y (n_698));
  INVX1 g13927(.A (n_620), .Y (n_696));
  CLKINVX1 g13928(.A (n_614), .Y (n_668));
  CLKINVX1 g13929(.A (n_611), .Y (n_669));
  NAND2BXL g13931(.AN (tx_state[1]), .B (tx_state[0]), .Y (n_604));
  NAND2XL g13932(.A (tx_tick_cnt[0]), .B (tx_tick_cnt[1]), .Y (n_664));
  NOR2XL g13933(.A (TXEN), .B (reg_ctrl[1]), .Y (n_620));
  NOR2XL g13934(.A (reg_baud_cntr_i[9]), .B (reg_baud_cntr_i[10]), .Y
       (n_614));
  OR2X1 g13935(.A (reg_baud_cntr_i[11]), .B (reg_baud_cntr_i[12]), .Y
       (n_697));
  NOR2XL g13936(.A (PADDR[2]), .B (PADDR[3]), .Y (n_611));
  NAND2BX1 g13937(.AN (PWRITE), .B (PSEL), .Y (n_704));
  INVX1 g13939(.A (reg_baud_div[3]), .Y (n_598));
  INVX1 g13941(.A (reg_baud_div[1]), .Y (n_595));
  NAND2BXL g2(.AN (n_704), .B (n_633), .Y (n_663));
  DFFRHQX1 \read_mux_byte0_reg_reg[0] (.RN (PRESETn), .CK (PCLKG), .D
       (n_339), .Q (n_710));
  DFFRHQX1 \read_mux_byte0_reg_reg[1] (.RN (PRESETn), .CK (PCLKG), .D
       (n_316), .Q (read_mux_byte0_reg[1]));
  DFFRHQX1 \read_mux_byte0_reg_reg[2] (.RN (PRESETn), .CK (PCLKG), .D
       (n_317), .Q (read_mux_byte0_reg[2]));
  DFFRHQX1 \read_mux_byte0_reg_reg[3] (.RN (PRESETn), .CK (PCLKG), .D
       (n_355), .Q (n_709));
  DFFRHQX1 \read_mux_byte0_reg_reg[4] (.RN (PRESETn), .CK (PCLKG), .D
       (n_362), .Q (read_mux_byte0_reg[4]));
  DFFRHQX1 \read_mux_byte0_reg_reg[5] (.RN (PRESETn), .CK (PCLKG), .D
       (n_333), .Q (read_mux_byte0_reg[5]));
  DFFRHQX1 \read_mux_byte0_reg_reg[6] (.RN (PRESETn), .CK (PCLKG), .D
       (n_347), .Q (n_708));
  DFFRHQX1 \read_mux_byte0_reg_reg[7] (.RN (PRESETn), .CK (PCLKG), .D
       (n_328), .Q (read_mux_byte0_reg[7]));
  DFFRHQX1 \reg_baud_cntr_f_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (n_374), .Q (reg_baud_cntr_f[3]));
  DFFRHQX1 \reg_baud_cntr_i_reg[4] (.RN (PRESETn), .CK (PCLK), .D
       (n_387), .Q (reg_baud_cntr_i[4]));
  DFFRHQX1 \reg_baud_cntr_i_reg[5] (.RN (PRESETn), .CK (PCLK), .D
       (n_401), .Q (reg_baud_cntr_i[5]));
  DFFRHQX1 \reg_baud_cntr_i_reg[6] (.RN (PRESETn), .CK (PCLK), .D
       (n_434), .Q (reg_baud_cntr_i[6]));
  DFFRHQX1 \reg_baud_cntr_i_reg[8] (.RN (PRESETn), .CK (PCLK), .D
       (n_458), .Q (reg_baud_cntr_i[8]));
  DFFRHQX1 \reg_baud_cntr_i_reg[10] (.RN (PRESETn), .CK (PCLK), .D
       (n_523), .Q (reg_baud_cntr_i[10]));
  DFFRHQX1 \reg_baud_cntr_i_reg[11] (.RN (PRESETn), .CK (PCLK), .D
       (n_501), .Q (reg_baud_cntr_i[11]));
  DFFRHQX1 \reg_baud_cntr_i_reg[12] (.RN (PRESETn), .CK (PCLK), .D
       (n_550), .Q (reg_baud_cntr_i[12]));
  DFFRHQX1 \reg_baud_cntr_i_reg[13] (.RN (PRESETn), .CK (PCLK), .D
       (n_549), .Q (reg_baud_cntr_i[13]));
  DFFRHQX1 \reg_baud_cntr_i_reg[14] (.RN (PRESETn), .CK (PCLK), .D
       (n_545), .Q (reg_baud_cntr_i[14]));
  DFFRHQX1 \reg_baud_cntr_i_reg[15] (.RN (PRESETn), .CK (PCLK), .D
       (n_510), .Q (reg_baud_cntr_i[15]));
  SDFFRHQX1 \reg_baud_div_reg[0] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[0]), .SI (reg_baud_div[0]), .SE (n_750), .Q
       (reg_baud_div[0]));
  SDFFRHQX1 \reg_baud_div_reg[1] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[1]), .SI (reg_baud_div[1]), .SE (n_750), .Q
       (reg_baud_div[1]));
  SDFFRHQX1 \reg_baud_div_reg[2] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[2]), .SI (reg_baud_div[2]), .SE (n_750), .Q
       (reg_baud_div[2]));
  SDFFRHQX1 \reg_baud_div_reg[8] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[8]), .SI (reg_baud_div[8]), .SE (n_750), .Q
       (reg_baud_div[8]));
  SDFFRHQX1 \reg_baud_div_reg[9] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[9]), .SI (reg_baud_div[9]), .SE (n_750), .Q
       (reg_baud_div[9]));
  SDFFRHQX1 \reg_baud_div_reg[10] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[10]), .SI (reg_baud_div[10]), .SE (n_750), .Q
       (reg_baud_div[10]));
  SDFFRHQX1 \reg_baud_div_reg[11] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[11]), .SI (reg_baud_div[11]), .SE (n_750), .Q
       (reg_baud_div[11]));
  SDFFRHQX1 \reg_baud_div_reg[12] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[12]), .SI (reg_baud_div[12]), .SE (n_750), .Q
       (reg_baud_div[12]));
  SDFFRHQX1 \reg_baud_div_reg[13] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[13]), .SI (reg_baud_div[13]), .SE (n_750), .Q
       (reg_baud_div[13]));
  SDFFRHQX1 \reg_baud_div_reg[14] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[14]), .SI (reg_baud_div[14]), .SE (n_750), .Q
       (reg_baud_div[14]));
  SDFFRHQX1 \reg_baud_div_reg[15] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[15]), .SI (reg_baud_div[15]), .SE (n_750), .Q
       (reg_baud_div[15]));
  SDFFRHQX1 \reg_baud_div_reg[16] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[16]), .SI (reg_baud_div[16]), .SE (n_750), .Q
       (reg_baud_div[16]));
  SDFFRHQX1 \reg_baud_div_reg[17] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[17]), .SI (reg_baud_div[17]), .SE (n_750), .Q
       (reg_baud_div[17]));
  SDFFRHQX1 \reg_baud_div_reg[18] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[18]), .SI (reg_baud_div[18]), .SE (n_750), .Q
       (reg_baud_div[18]));
  SDFFRHQX1 \reg_baud_div_reg[19] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[19]), .SI (reg_baud_div[19]), .SE (n_750), .Q
       (reg_baud_div[19]));
  SDFFRHQX1 \reg_ctrl_reg[0] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[0]), .SI (TXEN), .SE (n_673), .Q (TXEN));
  SDFFRHQX1 \reg_ctrl_reg[4] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[4]), .SI (reg_ctrl[4]), .SE (n_673), .Q (reg_ctrl[4]));
  SDFFRHQX1 \reg_ctrl_reg[5] (.RN (PRESETn), .CK (PCLKG), .D
       (PWDATA[5]), .SI (reg_ctrl[5]), .SE (n_673), .Q (reg_ctrl[5]));
  DFFRHQX1 reg_rx_overrun_reg(.RN (PRESETn), .CK (PCLK), .D (n_169), .Q
       (reg_rx_overrun));
  DFFRHQX1 reg_tx_overrun_reg(.RN (PRESETn), .CK (PCLK), .D (n_176), .Q
       (reg_tx_overrun));
  SDFFRHQX1 \rx_state_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_144),
       .SI (n_195), .SE (rx_state[2]), .Q (rx_state[2]));
  DFFRHQX1 \rx_tick_cnt_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_250),
       .Q (rx_tick_cnt[0]));
  DFFRHQX1 \rx_tick_cnt_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_252),
       .Q (rx_tick_cnt[1]));
  DFFRHQX1 \rx_tick_cnt_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_222),
       .Q (rx_tick_cnt[2]));
  DFFRHQX1 \rx_tick_cnt_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_236),
       .Q (rx_tick_cnt[3]));
  DFFRHQX1 \tx_shift_buf_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_311),
       .Q (n_706));
  DFFRHQX1 \tx_shift_buf_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_325),
       .Q (n_581));
  DFFRHQX1 \tx_shift_buf_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_305),
       .Q (n_575));
  DFFRHQX1 \tx_shift_buf_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_304),
       .Q (n_571));
  DFFRHQX1 \tx_shift_buf_reg[4] (.RN (PRESETn), .CK (PCLK), .D (n_324),
       .Q (n_565));
  DFFRHQX1 \tx_shift_buf_reg[5] (.RN (PRESETn), .CK (PCLK), .D (n_322),
       .Q (n_564));
  DFFRHQX1 \tx_shift_buf_reg[6] (.RN (PRESETn), .CK (PCLK), .D (n_314),
       .Q (n_563));
  DFFRHQX1 \tx_shift_buf_reg[7] (.RN (PRESETn), .CK (PCLK), .D (n_286),
       .Q (n_561));
  DFFRHQX1 \tx_state_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_262), .Q
       (tx_state[1]));
  DFFRHQX1 \tx_state_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_231), .Q
       (tx_state[2]));
  SDFFRHQX1 \tx_state_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (tx_state[3]), .SI (n_66), .SE (n_194), .Q (tx_state[3]));
  SDFFRHQX1 \tx_tick_cnt_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_143),
       .SI (n_45), .SE (tx_tick_cnt[0]), .Q (tx_tick_cnt[0]));
  DFFRHQX1 \tx_tick_cnt_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_226),
       .Q (tx_tick_cnt[1]));
  DFFRHQX1 \tx_tick_cnt_reg[2] (.RN (PRESETn), .CK (PCLK), .D (n_230),
       .Q (n_705));
  DFFRHQX1 \tx_tick_cnt_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_228),
       .Q (tx_tick_cnt[3]));
  OAI21XL g16648(.A0 (n_435), .A1 (n_697), .B0 (n_522), .Y (n_550));
  OAI21XL g16649(.A0 (n_435), .A1 (n_670), .B0 (n_516), .Y (n_549));
  OAI21XL g16650(.A0 (n_435), .A1 (n_665), .B0 (n_512), .Y (n_545));
  NAND2XL g16651(.A (n_435), .B (n_506), .Y (n_523));
  AOI22XL g16652(.A0 (n_452), .A1 (reg_baud_cntr_i[12]), .B0 (n_75),
       .B1 (reg_baud_div[16]), .Y (n_522));
  AOI22XL g16654(.A0 (n_445), .A1 (reg_baud_cntr_i[13]), .B0 (n_75),
       .B1 (reg_baud_div[17]), .Y (n_516));
  AOI22XL g16655(.A0 (n_447), .A1 (reg_baud_cntr_i[14]), .B0 (n_75),
       .B1 (reg_baud_div[18]), .Y (n_512));
  AO22X1 g16656(.A0 (reg_baud_cntr_i[15]), .A1 (n_451), .B0
       (reg_baud_div[19]), .B1 (n_75), .Y (n_510));
  AOI22XL g16659(.A0 (n_439), .A1 (reg_baud_cntr_i[10]), .B0 (n_75),
       .B1 (reg_baud_div[14]), .Y (n_506));
  OAI211XL g16660(.A0 (n_435), .A1 (reg_baud_cntr_i[11]), .B0 (n_157),
       .C0 (n_490), .Y (n_501));
  NAND2XL g16661(.A (reg_baud_cntr_i[11]), .B (n_440), .Y (n_490));
  NAND2XL g16662(.A (n_432), .B (n_438), .Y (n_458));
  OAI2BB1XL g16663(.A0N (reg_baud_cntr_i[11]), .A1N (n_141), .B0
       (n_441), .Y (n_452));
  OAI2BB1XL g16664(.A0N (n_665), .A1N (n_141), .B0 (n_441), .Y (n_451));
  OAI2BB1XL g16665(.A0N (n_670), .A1N (n_141), .B0 (n_441), .Y (n_447));
  OAI2BB1XL g16666(.A0N (n_697), .A1N (n_141), .B0 (n_441), .Y (n_445));
  OAI221XL g16667(.A0 (n_36), .A1 (n_437), .B0 (reg_baud_cntr_i[9]),
       .B1 (n_432), .C0 (n_158), .Y (n_442));
  CLKINVX1 g16670(.A (n_440), .Y (n_441));
  OAI21XL g16671(.A0 (n_142), .A1 (n_36), .B0 (n_437), .Y (n_439));
  AOI22XL g16672(.A0 (n_429), .A1 (reg_baud_cntr_i[8]), .B0 (n_75), .B1
       (reg_baud_div[12]), .Y (n_438));
  OAI2BB1XL g16673(.A0N (n_668), .A1N (n_141), .B0 (n_437), .Y (n_440));
  AOI21XL g16674(.A0 (reg_baud_cntr_i[8]), .A1 (n_141), .B0 (n_429), .Y
       (n_437));
  OR2X1 g16675(.A (n_668), .B (n_432), .Y (n_435));
  NAND2XL g16676(.A (n_388), .B (n_426), .Y (n_434));
  OAI21XL g16677(.A0 (n_411), .A1 (n_13), .B0 (n_428), .Y (n_433));
  NAND2BXL g16678(.AN (reg_baud_cntr_i[8]), .B (n_415), .Y (n_432));
  AOI21XL g16680(.A0 (reg_baud_div[11]), .A1 (n_75), .B0 (n_415), .Y
       (n_428));
  AOI22XL g16681(.A0 (n_393), .A1 (reg_baud_cntr_i[6]), .B0 (n_75), .B1
       (reg_baud_div[10]), .Y (n_426));
  OAI21XL g16682(.A0 (n_142), .A1 (n_13), .B0 (n_411), .Y (n_429));
  NOR2XL g16683(.A (reg_baud_cntr_i[7]), .B (n_388), .Y (n_415));
  OAI211XL g16684(.A0 (n_381), .A1 (n_142), .B0 (n_159), .C0 (n_160),
       .Y (n_401));
  AOI21XL g16685(.A0 (reg_baud_cntr_i[6]), .A1 (n_141), .B0 (n_393), .Y
       (n_411));
  OAI21XL g16686(.A0 (n_375), .A1 (n_142), .B0 (n_76), .Y (n_393));
  NAND3BXL g16687(.AN (reg_baud_cntr_i[6]), .B (n_141), .C (n_375), .Y
       (n_388));
  OAI211XL g16689(.A0 (n_366), .A1 (n_142), .B0 (n_161), .C0 (n_162),
       .Y (n_387));
  AOI21XL g16690(.A0 (reg_baud_cntr_i[5]), .A1 (n_351), .B0 (n_375), .Y
       (n_381));
  NOR2XL g16692(.A (reg_baud_cntr_i[5]), .B (n_351), .Y (n_375));
  OAI211XL g16696(.A0 (n_298), .A1 (reg_baud_cntr_f[3]), .B0 (n_720),
       .C0 (n_345), .Y (n_374));
  OAI222XL g16697(.A0 (n_817), .A1 (n_74), .B0 (n_315), .B1 (n_142),
       .C0 (n_76), .C1 (n_28), .Y (n_372));
  AOI21XL g16701(.A0 (reg_baud_cntr_i[4]), .A1 (n_290), .B0 (n_350), .Y
       (n_366));
  NAND2BXL g16702(.AN (n_288), .B (n_335), .Y (n_362));
  OR4X1 g16703(.A (n_288), .B (n_276), .C (n_312), .D (n_257), .Y
       (n_355));
  CLKINVX1 g16711(.A (n_350), .Y (n_351));
  OAI211XL g16712(.A0 (n_820), .A1 (n_725), .B0 (n_140), .C0 (n_300),
       .Y (n_347));
  NAND2XL g16713(.A (reg_baud_cntr_f[3]), .B (n_298), .Y (n_345));
  OAI211XL g16714(.A0 (n_221), .A1 (n_15), .B0 (n_720), .C0 (n_298), .Y
       (n_341));
  NAND4BXL g16715(.AN (n_288), .B (n_128), .C (n_238), .D (n_313), .Y
       (n_339));
  AOI211XL g16716(.A0 (read_mux_byte0_reg[4]), .A1 (n_704), .B0
       (n_113), .C0 (n_331), .Y (n_335));
  OAI211XL g16717(.A0 (n_809), .A1 (n_725), .B0 (n_112), .C0 (n_320),
       .Y (n_333));
  NOR2XL g16718(.A (reg_baud_cntr_i[4]), .B (n_290), .Y (n_350));
  OAI22XL g16719(.A0 (n_278), .A1 (n_104), .B0 (n_146), .B1 (n_11), .Y
       (n_332));
  OAI211XL g16726(.A0 (n_794), .A1 (n_725), .B0 (n_277), .C0 (n_209),
       .Y (n_331));
  OAI211XL g16727(.A0 (n_269), .A1 (n_164), .B0 (n_89), .C0 (n_123), .Y
       (n_328));
  OAI222XL g16728(.A0 (n_731), .A1 (n_74), .B0 (n_234), .B1 (n_142),
       .C0 (n_76), .C1 (n_32), .Y (n_327));
  OAI211XL g16729(.A0 (n_727), .A1 (n_811), .B0 (n_291), .C0 (n_246),
       .Y (n_325));
  OAI211XL g16730(.A0 (n_727), .A1 (n_813), .B0 (n_295), .C0 (n_249),
       .Y (n_324));
  OAI211XL g16731(.A0 (n_727), .A1 (n_799), .B0 (n_285), .C0 (n_239),
       .Y (n_322));
  AOI211XL g16732(.A0 (n_178), .A1 (reg_ctrl[5]), .B0 (n_108), .C0
       (n_319), .Y (n_320));
  OAI22XL g16733(.A0 (n_269), .A1 (n_107), .B0 (n_256), .B1 (n_84), .Y
       (n_319));
  OAI211XL g16734(.A0 (n_179), .A1 (n_753), .B0 (n_259), .C0 (n_261),
       .Y (n_317));
  NAND4BXL g16735(.AN (n_288), .B (n_225), .C (n_227), .D (n_224), .Y
       (n_316));
  AOI21XL g16736(.A0 (reg_baud_cntr_i[3]), .A1 (n_206), .B0 (n_289), .Y
       (n_315));
  OAI211XL g16740(.A0 (n_727), .A1 (n_812), .B0 (n_287), .C0 (n_248),
       .Y (n_314));
  AOI211XL g16741(.A0 (n_178), .A1 (TXEN), .B0 (n_264), .C0 (n_109), .Y
       (n_313));
  OAI22XL g16742(.A0 (n_269), .A1 (n_84), .B0 (n_798), .B1 (n_725), .Y
       (n_312));
  OAI211XL g16743(.A0 (n_727), .A1 (n_819), .B0 (n_292), .C0 (n_247),
       .Y (n_311));
  OAI211XL g16744(.A0 (n_727), .A1 (n_814), .B0 (n_293), .C0 (n_245),
       .Y (n_305));
  OAI211XL g16745(.A0 (n_727), .A1 (n_810), .B0 (n_294), .C0 (n_240),
       .Y (n_304));
  AOI22XL g16746(.A0 (n_271), .A1 (n_172), .B0 (n_178), .B1
       (reg_ctrl[6]), .Y (n_300));
  NAND2XL g16747(.A (n_564), .B (n_268), .Y (n_295));
  NAND2XL g16748(.A (n_565), .B (n_268), .Y (n_294));
  NAND2XL g16749(.A (n_571), .B (n_268), .Y (n_293));
  NAND2XL g16750(.A (n_581), .B (n_268), .Y (n_292));
  NAND2XL g16751(.A (n_575), .B (n_268), .Y (n_291));
  NAND2XL g16752(.A (n_15), .B (n_221), .Y (n_298));
  CLKINVX1 g16757(.A (n_289), .Y (n_290));
  NAND2XL g16758(.A (n_561), .B (n_268), .Y (n_287));
  OAI211XL g16759(.A0 (n_727), .A1 (n_803), .B0 (n_267), .C0 (n_111),
       .Y (n_286));
  NAND2XL g16760(.A (n_563), .B (n_268), .Y (n_285));
  AOI21XL g16761(.A0 (rx_state[0]), .A1 (n_751), .B0 (n_258), .Y
       (n_278));
  OAI21XL g16762(.A0 (n_78), .A1 (ECOREVNUM[0]), .B0 (n_271), .Y
       (n_277));
  OAI22XL g16763(.A0 (n_256), .A1 (n_662), .B0 (n_179), .B1 (n_752), .Y
       (n_276));
  NAND2XL g16764(.A (n_720), .B (n_235), .Y (n_273));
  OAI222XL g16765(.A0 (n_733), .A1 (n_208), .B0 (n_20), .B1 (n_76), .C0
       (n_142), .C1 (reg_baud_cntr_i[0]), .Y (n_272));
  NOR2XL g16766(.A (reg_baud_cntr_i[3]), .B (n_206), .Y (n_289));
  NOR3XL g16767(.A (PADDR[2]), .B (n_78), .C (n_256), .Y (n_288));
  INVX1 g16777(.A (n_271), .Y (n_269));
  INVXL g16778(.A (n_268), .Y (n_267));
  OAI222XL g16779(.A0 (n_732), .A1 (n_74), .B0 (n_135), .B1 (n_142),
       .C0 (n_76), .C1 (n_31), .Y (n_266));
  AOI21XL g16780(.A0 (n_73), .A1 (n_669), .B0 (n_256), .Y (n_264));
  AOI211XL g16781(.A0 (n_80), .A1 (n_87), .B0 (n_38), .C0 (n_198), .Y
       (n_263));
  OAI211XL g16782(.A0 (n_194), .A1 (n_68), .B0 (n_147), .C0 (n_196), .Y
       (n_262));
  AOI221XL g16783(.A0 (reg_ctrl[2]), .A1 (n_178), .B0
       (reg_baud_div[2]), .B1 (n_49), .C0 (n_129), .Y (n_261));
  AOI22XL g16784(.A0 (n_207), .A1 (n_173), .B0 (n_191), .B1
       (reg_tx_overrun), .Y (n_259));
  OAI32XL g16785(.A0 (n_193), .A1 (rx_state[0]), .A2 (n_751), .B0
       (n_217), .B1 (n_737), .Y (n_258));
  OAI211XL g16786(.A0 (n_818), .A1 (n_730), .B0 (n_72), .C0 (n_223), .Y
       (n_257));
  NOR2XL g16787(.A (n_55), .B (n_256), .Y (n_271));
  NOR2XL g16788(.A (n_237), .B (n_119), .Y (n_268));
  NOR2XL g16789(.A (n_121), .B (n_216), .Y (n_252));
  NOR2XL g16790(.A (n_132), .B (n_216), .Y (n_250));
  NAND2XL g16791(.A (n_565), .B (n_202), .Y (n_249));
  NAND2XL g16792(.A (n_563), .B (n_202), .Y (n_248));
  NAND2XL g16793(.A (n_706), .B (n_202), .Y (n_247));
  NAND2XL g16794(.A (n_581), .B (n_202), .Y (n_246));
  NAND2XL g16795(.A (n_575), .B (n_202), .Y (n_245));
  NAND2XL g16796(.A (n_571), .B (n_202), .Y (n_240));
  NAND2XL g16797(.A (n_564), .B (n_202), .Y (n_239));
  NAND2XL g16799(.A (PADDR[5]), .B (n_207), .Y (n_256));
  AOI22XL g16803(.A0 (n_191), .A1 (tx_buf_full), .B0 (n_185), .B1
       (TXINT), .Y (n_238));
  OAI31XL g16804(.A0 (n_23), .A1 (tx_state[2]), .A2 (n_147), .B0
       (n_659), .Y (n_237));
  OAI2BB1XL g16805(.A0N (n_110), .A1N (n_751), .B0 (n_217), .Y (n_236));
  AOI21XL g16806(.A0 (reg_baud_cntr_f[1]), .A1 (n_116), .B0 (n_221), .Y
       (n_235));
  OA21X1 g16807(.A0 (n_32), .A1 (n_83), .B0 (n_206), .Y (n_234));
  OAI21XL g16808(.A0 (n_82), .A1 (n_698), .B0 (n_210), .Y (n_231));
  AO22X1 g16809(.A0 (n_67), .A1 (n_143), .B0 (n_705), .B1 (n_823), .Y
       (n_230));
  AO22X1 g16810(.A0 (n_62), .A1 (n_143), .B0 (tx_tick_cnt[3]), .B1
       (n_822), .Y (n_228));
  OA22X1 g16811(.A0 (n_40), .A1 (n_179), .B0 (n_725), .B1 (n_805), .Y
       (n_227));
  AO22X1 g16812(.A0 (tx_tick_cnt[0]), .A1 (n_175), .B0
       (tx_tick_cnt[1]), .B1 (n_177), .Y (n_226));
  AOI22XL g16813(.A0 (n_191), .A1 (rx_buf_full), .B0
       (read_mux_byte0_reg[1]), .B1 (n_704), .Y (n_225));
  AOI22XL g16814(.A0 (n_178), .A1 (reg_ctrl[1]), .B0 (n_49), .B1
       (reg_baud_div[1]), .Y (n_224));
  AOI22XL g16815(.A0 (n_191), .A1 (reg_rx_overrun), .B0 (n_178), .B1
       (reg_ctrl[3]), .Y (n_223));
  NOR2XL g16816(.A (n_122), .B (n_216), .Y (n_222));
  INVX1 g16817(.A (n_217), .Y (n_216));
  NAND2XL g16819(.A (tx_state[2]), .B (n_170), .Y (n_210));
  NAND2XL g16820(.A (reg_ctrl[4]), .B (n_178), .Y (n_209));
  AOI221XL g16821(.A0 (reg_baud_cntr_i[0]), .A1 (n_63), .B0 (n_20), .B1
       (n_696), .C0 (baud_updated), .Y (n_208));
  NOR2XL g16823(.A (reg_baud_cntr_f[1]), .B (n_116), .Y (n_221));
  NAND2XL g16825(.A (n_700), .B (n_193), .Y (n_217));
  OAI2BB1XL g16826(.A0N (rx_state[2]), .A1N (n_144), .B0 (n_126), .Y
       (n_201));
  AOI211XL g16827(.A0 (n_117), .A1 (TXEN), .B0 (tx_state[0]), .C0
       (n_120), .Y (n_198));
  NAND3XL g16828(.A (n_720), .B (n_103), .C (n_116), .Y (n_197));
  NAND4BXL g16829(.AN (n_698), .B (tx_state[0]), .C (n_87), .D (n_661),
       .Y (n_196));
  OAI211XL g16830(.A0 (n_39), .A1 (rx_state[3]), .B0 (rx_state[1]), .C0
       (n_146), .Y (n_195));
  NOR3XL g16831(.A (n_64), .B (n_704), .C (n_130), .Y (n_207));
  NAND2XL g16832(.A (n_32), .B (n_83), .Y (n_206));
  AOI221XL g16833(.A0 (n_23), .A1 (n_117), .B0 (n_698), .B1 (n_738),
       .C0 (n_194), .Y (n_202));
  CLKINVX1 g16834(.A (n_82), .Y (n_194));
  INVX1 g16851(.A (n_179), .Y (n_185));
  OAI21XL g16852(.A0 (n_80), .A1 (tx_tick_cnt[0]), .B0 (BAUDTICK), .Y
       (n_177));
  OAI21XL g16853(.A0 (n_118), .A1 (n_702), .B0 (n_148), .Y (n_176));
  NOR2BXL g16854(.AN (n_143), .B (tx_tick_cnt[1]), .Y (n_175));
  OAI21XL g16855(.A0 (n_751), .A1 (n_85), .B0 (rx_state[1]), .Y
       (n_174));
  OAI21XL g16856(.A0 (n_69), .A1 (PADDR[2]), .B0 (n_662), .Y (n_173));
  OAI21XL g16857(.A0 (n_51), .A1 (PADDR[3]), .B0 (n_3), .Y (n_172));
  OAI211XL g16858(.A0 (n_738), .A1 (tx_state[3]), .B0 (tx_state[1]),
       .C0 (tx_state[0]), .Y (n_170));
  OAI21XL g16859(.A0 (n_701), .A1 (n_656), .B0 (n_165), .Y (n_169));
  NOR3BXL g16862(.AN (n_85), .B (rx_state[1]), .C (rx_state[2]), .Y
       (n_193));
  NOR3XL g16866(.A (n_55), .B (n_84), .C (n_663), .Y (n_191));
  NAND2XL g16867(.A (PADDR[2]), .B (n_166), .Y (n_179));
  NOR2BXL g16868(.AN (n_166), .B (PADDR[2]), .Y (n_178));
  OAI21XL g16869(.A0 (n_660), .A1 (n_42), .B0 (reg_rx_overrun), .Y
       (n_165));
  NOR2XL g16870(.A (ECOREVNUM[3]), .B (n_78), .Y (n_164));
  NAND2XL g16871(.A (n_702), .B (n_118), .Y (n_163));
  NAND2XL g16872(.A (reg_baud_div[8]), .B (n_75), .Y (n_162));
  NAND2XL g16873(.A (reg_baud_cntr_i[4]), .B (n_2), .Y (n_161));
  NAND2XL g16874(.A (reg_baud_div[9]), .B (n_75), .Y (n_160));
  NAND2XL g16875(.A (reg_baud_cntr_i[5]), .B (n_2), .Y (n_159));
  NAND2XL g16877(.A (reg_baud_div[13]), .B (n_75), .Y (n_158));
  NAND2XL g16878(.A (reg_baud_div[15]), .B (n_75), .Y (n_157));
  OAI21XL g16881(.A0 (n_660), .A1 (n_57), .B0 (reg_tx_overrun), .Y
       (n_148));
  NOR2XL g16882(.A (n_78), .B (n_663), .Y (n_166));
  CLKINVX1 g16883(.A (n_142), .Y (n_141));
  AOI21XL g16884(.A0 (n_704), .A1 (n_708), .B0 (n_106), .Y (n_140));
  AOI21XL g16885(.A0 (reg_baud_cntr_i[1]), .A1 (reg_baud_cntr_i[0]),
       .B0 (n_83), .Y (n_135));
  MXI2XL g16886(.A (BAUDTICK), .B (n_45), .S0 (rx_tick_cnt[0]), .Y
       (n_132));
  NAND4XL g16887(.A (PADDR[8]), .B (PADDR[9]), .C (PADDR[10]), .D
       (PADDR[11]), .Y (n_130));
  AO22X1 g16888(.A0 (reg_rx_buf[2]), .A1 (n_37), .B0 (n_704), .B1
       (read_mux_byte0_reg[2]), .Y (n_129));
  AOI22XL g16889(.A0 (n_49), .A1 (reg_baud_div[0]), .B0 (n_710), .B1
       (n_704), .Y (n_128));
  OAI21XL g16890(.A0 (n_751), .A1 (n_16), .B0 (rx_state[3]), .Y
       (n_126));
  AOI22XL g16891(.A0 (n_37), .A1 (reg_rx_buf[7]), .B0
       (read_mux_byte0_reg[7]), .B1 (n_704), .Y (n_123));
  AOI21XL g16892(.A0 (rx_tick_cnt[2]), .A1 (n_666), .B0 (n_105), .Y
       (n_122));
  AOI21XL g16893(.A0 (rx_tick_cnt[1]), .A1 (n_672), .B0 (n_90), .Y
       (n_121));
  NAND3XL g16894(.A (tx_buf_full), .B (tx_state[1]), .C (tx_state[3]),
       .Y (n_147));
  OAI21XL g16895(.A0 (n_59), .A1 (n_737), .B0 (n_751), .Y (n_146));
  NOR3XL g16896(.A (rx_state[3]), .B (n_16), .C (n_667), .Y (n_144));
  NOR2XL g16897(.A (n_45), .B (n_80), .Y (n_143));
  NAND3XL g16898(.A (n_696), .B (n_720), .C (n_729), .Y (n_142));
  INVX1 g16899(.A (n_119), .Y (n_120));
  NOR2XL g16900(.A (n_730), .B (n_733), .Y (n_113));
  NAND2XL g16901(.A (n_704), .B (read_mux_byte0_reg[5]), .Y (n_112));
  NAND2XL g16902(.A (n_561), .B (n_727), .Y (n_111));
  NAND2BXL g16903(.AN (rx_tick_cnt[3]), .B (n_658), .Y (n_110));
  NOR2XL g16904(.A (n_725), .B (n_802), .Y (n_109));
  NOR2XL g16905(.A (n_730), .B (n_732), .Y (n_108));
  NOR2XL g16906(.A (ECOREVNUM[1]), .B (PADDR[4]), .Y (n_107));
  NOR2XL g16907(.A (n_730), .B (n_731), .Y (n_106));
  NOR2XL g16908(.A (rx_tick_cnt[2]), .B (n_666), .Y (n_105));
  NOR2XL g16909(.A (n_4), .B (n_16), .Y (n_104));
  NAND2XL g16910(.A (n_707), .B (n_726), .Y (n_103));
  NOR2XL g16911(.A (rx_tick_cnt[1]), .B (n_672), .Y (n_90));
  NAND2XL g16912(.A (reg_baud_div[7]), .B (n_49), .Y (n_89));
  NAND2XL g16913(.A (n_671), .B (n_738), .Y (n_119));
  NAND2XL g16914(.A (tx_buf_full), .B (n_727), .Y (n_118));
  NOR2XL g16915(.A (n_7), .B (n_671), .Y (n_117));
  OR2X1 g16916(.A (n_707), .B (n_726), .Y (n_116));
  CLKINVX1 g16917(.A (n_80), .Y (n_81));
  CLKINVX1 g16919(.A (n_2), .Y (n_76));
  INVX1 g16920(.A (n_75), .Y (n_74));
  NAND2XL g16921(.A (PADDR[3]), .B (PADDR[4]), .Y (n_73));
  NAND2XL g16922(.A (n_704), .B (n_709), .Y (n_72));
  NAND2XL g16923(.A (PADDR[4]), .B (PADDR[5]), .Y (n_69));
  NOR2XL g16924(.A (tx_state[1]), .B (n_38), .Y (n_68));
  NOR2XL g16925(.A (n_705), .B (n_664), .Y (n_67));
  NOR2BXL g16926(.AN (tx_state[2]), .B (tx_state[3]), .Y (n_66));
  NAND2XL g16927(.A (PADDR[6]), .B (PADDR[7]), .Y (n_64));
  NOR2XL g16928(.A (n_728), .B (n_729), .Y (n_63));
  NOR2XL g16929(.A (tx_tick_cnt[3]), .B (n_703), .Y (n_62));
  NOR2XL g16930(.A (reg_ctrl[6]), .B (n_45), .Y (n_87));
  NOR2XL g16931(.A (rx_state[0]), .B (rx_state[3]), .Y (n_85));
  OR2X1 g16932(.A (PADDR[3]), .B (PADDR[4]), .Y (n_84));
  NOR2XL g16933(.A (reg_baud_cntr_i[1]), .B (reg_baud_cntr_i[0]), .Y
       (n_83));
  NAND2XL g16934(.A (tx_state[1]), .B (n_38), .Y (n_82));
  NOR2XL g16935(.A (n_23), .B (n_671), .Y (n_80));
  NAND2XL g16936(.A (PADDR[3]), .B (n_51), .Y (n_78));
  NAND2BXL g16938(.AN (baud_updated), .B (n_726), .Y (n_75));
  INVX1 g16940(.A (PWDATA[2]), .Y (n_57));
  CLKINVX1 g16945(.A (PADDR[2]), .Y (n_55));
  CLKINVX1 g16946(.A (PADDR[4]), .Y (n_51));
  INVX1 g16950(.A (n_730), .Y (n_49));
  INVX1 g16952(.A (PWDATA[3]), .Y (n_42));
  INVXL g16953(.A (RXINT), .Y (n_40));
  INVX1 g16954(.A (n_667), .Y (n_39));
  INVX1 g16955(.A (n_699), .Y (n_38));
  CLKINVX1 g16962(.A (n_725), .Y (n_37));
  DFFRX1 \reg_baud_cntr_f_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (n_341), .Q (reg_baud_cntr_f[2]), .QN (n_15));
  DFFRX1 \reg_baud_cntr_i_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (n_272), .Q (reg_baud_cntr_i[0]), .QN (n_20));
  DFFRX1 \reg_baud_cntr_i_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (n_266), .Q (reg_baud_cntr_i[1]), .QN (n_31));
  DFFRX1 \reg_baud_cntr_i_reg[2] (.RN (PRESETn), .CK (PCLK), .D
       (n_327), .Q (reg_baud_cntr_i[2]), .QN (n_32));
  DFFRX1 \reg_baud_cntr_i_reg[3] (.RN (PRESETn), .CK (PCLK), .D
       (n_372), .Q (reg_baud_cntr_i[3]), .QN (n_28));
  DFFRX1 \reg_baud_cntr_i_reg[7] (.RN (PRESETn), .CK (PCLK), .D
       (n_433), .Q (reg_baud_cntr_i[7]), .QN (n_13));
  DFFRX1 \reg_baud_cntr_i_reg[9] (.RN (PRESETn), .CK (PCLK), .D
       (n_442), .Q (reg_baud_cntr_i[9]), .QN (n_36));
  DFFRX1 \rx_state_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_332), .Q
       (rx_state[0]), .QN (n_11));
  DFFRX1 \rx_state_reg[1] (.RN (PRESETn), .CK (PCLK), .D (n_821), .Q
       (rx_state[1]), .QN (n_16));
  DFFRX1 \rx_state_reg[3] (.RN (PRESETn), .CK (PCLK), .D (n_201), .Q
       (rx_state[3]), .QN (n_4));
  DFFRX1 tx_buf_full_reg(.RN (PRESETn), .CK (PCLK), .D (n_163), .Q
       (tx_buf_full), .QN (n_7));
  DFFRX1 \tx_state_reg[0] (.RN (PRESETn), .CK (PCLK), .D (n_263), .Q
       (tx_state[0]), .QN (n_23));
  NAND2BXL g13943(.AN (n_78), .B (ECOREVNUM[2]), .Y (n_3));
  NOR2BX1 g16987(.AN (n_720), .B (n_696), .Y (n_2));
  DFFRX1 \reg_baud_cntr_f_reg[0] (.RN (PRESETn), .CK (PCLK), .D
       (n_197), .Q (n_707), .QN (n_597));
  DFFRX1 \reg_baud_cntr_f_reg[1] (.RN (PRESETn), .CK (PCLK), .D
       (n_273), .Q (reg_baud_cntr_f[1]), .QN (n_594));
  DFFRX1 reg_baud_tick_reg(.RN (PRESETn), .CK (PCLK), .D (n_641), .Q
       (BAUDTICK), .QN (n_45));
  NAND2BX1 g16994(.AN (n_645), .B (n_174), .Y (n_821));
  OAI2BB1X1 g16995(.A0N (n_703), .A1N (n_81), .B0 (BAUDTICK), .Y
       (n_822));
  OAI2BB1X1 g16996(.A0N (n_664), .A1N (n_81), .B0 (BAUDTICK), .Y
       (n_823));
endmodule
